// Hindi for symptom labels and self-care tips (draft, pending clinician review)
export const HI_DATA: Record<string, string> = {
  // mother - RED
  "Heavy bleeding (soaking a pad within an hour)": "बहुत ज़्यादा खून बहना (एक घंटे में पैड भीग जाना)",
  "Large blood clots": "खून के बड़े थक्के",
  "Fits or seizure": "दौरे पड़ना (झटके आना)",
  "Fainting or blacking out": "बेहोश होना या आँखों के आगे अँधेरा छा जाना",
  "Chest pain": "सीने में दर्द",
  "Breathlessness": "साँस फूलना",
  "Fever with chills": "ठंड लगने के साथ बुखार",
  "Foul-smelling discharge": "बदबूदार स्राव",
  "Painful swollen calf on one side": "एक तरफ़ की पिंडली में दर्द और सूजन",
  "Thoughts of harming myself or the baby": "खुद को या बच्चे को नुकसान पहुँचाने के विचार",
  "Very high blood pressure reading": "ब्लड प्रेशर की बहुत ऊँची रीडिंग",
  // mother - AMBER
  "Painful red breast": "स्तन में दर्द और लालिमा",
  "Burning while passing urine": "पेशाब करते समय जलन",
  "Persistent low mood": "लगातार उदास मन",
  "Persistent anxiety or worry": "लगातार चिंता या घबराहट",
  "Not sleeping even when baby sleeps": "बच्चे के सोने पर भी नींद न आना",
  "Unable to eat": "खाना न खा पाना",
  "Severe pain that is getting worse": "तेज़ दर्द जो बढ़ता जा रहा है",
  "Cannot control urine": "पेशाब पर नियंत्रण न रहना",
  "Hard, engorged breasts": "सख़्त, दूध से भरे हुए भारी स्तन",
  "Sudden heavy hair fall with weakness": "कमज़ोरी के साथ अचानक बहुत बाल झड़ना",
  // mother - GREEN
  "Mild afterpains / cramps": "प्रसव के बाद हल्का दर्द / ऐंठन",
  "Light bleeding that is reducing": "हल्का खून आना जो कम हो रहा है",
  "Tiredness": "थकान",
  "Brief tearfulness (first 2 weeks)": "थोड़ी देर के लिए रोना आना (पहले 2 सप्ताह)",
  "Mild back or body ache": "हल्का कमर या बदन दर्द",
  "Constipation": "कब्ज़",
  "Sore nipples": "निप्पल में दर्द",
  "Hair fall": "बाल झड़ना",
  "Night sweats": "रात में पसीना आना",
  // baby
  "Baby is not feeding": "बच्चा दूध नहीं पी रहा",
  "Baby has convulsions": "बच्चे को झटके (दौरे) आ रहे हैं",
  "Fast breathing (60+ a minute)": "तेज़ साँस (प्रति मिनट 60 या अधिक)",
  "Chest indrawing": "साँस लेते समय छाती का अंदर धँसना",
  "Very high or very low temperature": "बहुत ज़्यादा या बहुत कम तापमान",
  "Unusually drowsy or limp": "असामान्य रूप से सुस्त या ढीला पड़ा हुआ",
  "Yellow skin in first 24 hours": "पहले 24 घंटे में त्वचा का पीला पड़ना",
  "Spreading redness or pus at cord": "नाल के पास फैलती लालिमा या मवाद",
  "Yellowish skin or eyes": "त्वचा या आँखों का पीलापन",
  "Baby vomiting repeatedly": "बच्चे को बार-बार उल्टी",
  "Loose watery stools": "पतले, पानी जैसे दस्त",
  "Skin rash": "त्वचा पर दाने",
  "Hiccups or sneezing": "हिचकी या छींक",
  "Fussy crying in the evening": "शाम को चिड़चिड़ाकर रोना",
  // tips
  "Mild cramps are common while the womb shrinks. A warm compress and rest help. Feeding often brings them on.": "गर्भाशय के सिकुड़ने के दौरान हल्की ऐंठन आम है। गर्म सेंक और आराम से राहत मिलती है। दूध पिलाने पर यह अक्सर बढ़ती है।",
  "Bleeding (lochia) can last up to 6 weeks and should slowly get lighter. Watch for it getting heavier.": "प्रसव के बाद का रक्तस्राव (लोकिया) 6 सप्ताह तक चल सकता है और धीरे-धीरे हल्का होना चाहिए। ध्यान रखें कि वह ज़्यादा न होने लगे।",
  "Tiredness is very common. Sleep when the baby sleeps, accept help, drink water and eat regular meals.": "थकान बहुत आम है। बच्चे के सोने पर सो जाइए, मदद स्वीकार कीजिए, पानी पीजिए और नियमित भोजन कीजिए।",
  "Baby blues affect many mothers in the first two weeks. Talk to someone you trust. If it lasts longer, tell us.": "पहले दो सप्ताह में कई माँओं को बेबी ब्लूज़ होते हैं। किसी भरोसेमंद व्यक्ति से बात कीजिए। अगर यह लंबे समय तक रहे, तो हमें बताइए।",
  "Support your back while feeding and avoid lifting heavy things. Gentle walking helps.": "दूध पिलाते समय पीठ को सहारा दीजिए और भारी चीज़ें उठाने से बचिए। हल्की सैर से आराम मिलता है।",
  "Drink plenty of water, eat fibre (fruit, vegetables, dalia) and walk a little each day.": "खूब पानी पीजिए, रेशेदार चीज़ें (फल, सब्ज़ियाँ, दलिया) खाइए और रोज़ थोड़ा चलिए।",
  "A good latch matters most. Ask your ANM or a lactation consultant to check the latch.": "बच्चे का सही तरीके से स्तन पकड़ना (लैच) सबसे ज़रूरी है। अपनी एएनएम या स्तनपान सलाहकार से लैच जँचवाइए।",
  "Hair fall 2 to 4 months after birth is a normal hormone change and settles by itself.": "प्रसव के 2 से 4 महीने बाद बाल झड़ना हार्मोन में सामान्य बदलाव है और अपने आप ठीक हो जाता है।",
  "Night sweats happen as hormones settle. Keep water by the bed and wear light clothes.": "हार्मोन के संतुलित होने पर रात में पसीना आता है। बिस्तर के पास पानी रखिए और हल्के कपड़े पहनिए।",
  "Hiccups and sneezing are normal in newborns and settle by themselves.": "नवजात शिशुओं में हिचकी और छींक आना सामान्य है और अपने आप ठीक हो जाता है।",
  "Evening fussiness is common. Hold, swaddle, burp and feed. If crying is non-stop with fever or not feeding, use the checker again.": "शाम को चिड़चिड़ापन आम है। गोद में लीजिए, कपड़े में लपेटिए, डकार दिलाइए और दूध पिलाइए। अगर बुखार के साथ लगातार रोना हो या बच्चा दूध न पिए, तो लक्षण जाँच फिर से कीजिए।",
};
