import { HI_EXTRA } from "./hi-extra";
import { HI_DEPTH } from "./hi-depth";
import { HI_JOURNEY } from "./hi-journey";
// Hindi translations. Key = the English string used in the UI. Wording is a draft pending clinician review.
export const NAMES: [string, string][] = [
  ["Dr. Ananya Rao (sample)", "डॉ. अनन्या राव (नमूना)"],
  ["Anita Sharma (sample)", "अनीता शर्मा (नमूना)"],
  ["Sunita Devi (sample)", "सुनीता देवी (नमूना)"],
  ["Meera Iyer (sample)", "मीरा अय्यर (नमूना)"],
  ["Dr. Ananya Rao", "डॉ. अनन्या राव"],
  ["Ms. Neha Kulkarni", "सुश्री नेहा कुलकर्णी"],
  ["Dr. Vikram Sethi", "डॉ. विक्रम सेठी"],
  ["Bloom Buddy Kavita", "ब्लूम बडी कविता"],
  ["Priya", "प्रिया"],
  ["Verma", "वर्मा"],
  ["Aarav", "आरव"],
  ["Rohan", "रोहन"],
  ["Meera", "मीरा"],
  ["Delhi", "दिल्ली"],
];

// Patterns for strings that were stored with data already filled in
export const PATTERNS: [RegExp, (m: RegExpMatchArray, tr: (s: string) => string) => string][] = [
  [/^RED alert for (.+?): (.+)$/, (m, tr) => `${m[1]} के लिए लाल अलर्ट: ${tr(m[2])}`],
  [/^RED check-in for (.+?): (.+)$/, (m, tr) => `${m[1]} के चेक-इन में लाल अलर्ट: ${m[2].split(", ").map(tr).join(", ")}`],
  [/^EPDS (\d+): probable depression$/, (m) => `ईपीडीएस ${m[1]}: अवसाद की प्रबल संभावना`],
  [/^Viewed record of (.+)$/, (m) => `${m[1]} का रिकॉर्ड देखा`],
  [/^Viewed (.+?)'s weekly summary$/, (m) => `${m[1]} का साप्ताहिक सारांश देखा`],
  [/^Completed callback: (.+)$/, (m, tr) => `कॉलबैक पूरा किया: ${tr(m[1])}`],
  [/^Video room opened with (.+)$/, (m) => `${m[1]} के साथ वीडियो रूम खोला गया`],
  [/^(\d+) nights$/, (m) => `${m[1]} रातें`],
];

import { HI_DATA } from "./hi-data";
import { HI_GROUPING } from "./hi-grouping";
const BASE: Record<string, string> = {
  "Week 2": "सप्ताह 2", "Week 4": "सप्ताह 4",
  "BCG": "बीसीजी", "OPV-0": "ओपीवी-0", "OPV-1": "ओपीवी-1", "OPV-2": "ओपीवी-2", "OPV-3": "ओपीवी-3",
  "Pentavalent-1": "पेंटावैलेंट-1", "Pentavalent-2": "पेंटावैलेंट-2", "Pentavalent-3": "पेंटावैलेंट-3",
  "Rotavirus-1": "रोटावायरस-1", "Rotavirus-2": "रोटावायरस-2", "Rotavirus-3": "रोटावायरस-3",
  "fIPV-1": "एफ़आईपीवी-1", "fIPV-2": "एफ़आईपीवी-2", "PCV-1": "पीसीवी-1", "PCV-2": "पीसीवी-2",
  "MR-1": "एमआर-1", "MR-2": "एमआर-2", "JE-2": "जेई-2",
  "Your result will appear here. Describe how you feel, or pick a symptom from the list.": "आपका नतीजा यहाँ दिखेगा। बताइए कि आप कैसा महसूस कर रही हैं, या सूची में से कोई लक्षण चुनिए।",
  "SOS": "SOS",
  // ---------- navigation / shell ----------
  "Home": "होम", "Symptoms": "लक्षण", "Check-in": "चेक-इन", "Circles": "सर्कल", "More": "और",
  "Need help now": "अभी मदद चाहिए", "Quick exit": "तुरंत बाहर निकलें",
  "View: Mother": "दृश्य: माँ", "View: Family": "दृश्य: परिवार", "View: Professional": "दृश्य: विशेषज्ञ", "View as": "इस रूप में देखें",
  "Close menu": "मेनू बंद करें", "Open menu": "मेनू खोलें",
  "Day {n} postpartum": "प्रसव के बाद दिन {n}", "Family circle": "परिवार सर्कल", "Sample professional": "नमूना विशेषज्ञ",
  "Free help 24×7:": "मुफ़्त मदद 24×7:", "Tele-MANAS": "टेली-मानस", "Loading…": "लोड हो रहा है…",

  // ---------- features (sidebar / grid) ----------
  "Symptom checker": "लक्षण जाँच", "Is this normal? Tell us in your own words.": "क्या यह सामान्य है? अपने शब्दों में बताइए।",
  "Daily check-in": "दैनिक चेक-इन", "30 seconds. Mood, sleep, danger signs.": "30 सेकंड। मूड, नींद और ख़तरे के संकेत।",
  "Mind check (EPDS)": "मन की जाँच (ईपीडीएस)", "A routine wellness check for every new mother.": "हर नई माँ के लिए एक नियमित स्वास्थ्य जाँच।",
  "Talk to a professional": "विशेषज्ञ से बात करें", "Video sessions. Free Tele-MANAS always shown.": "वीडियो सत्र। मुफ़्त टेली-मानस हमेशा उपलब्ध।",
  "Bloom Circles": "ब्लूम सर्कल", "A small, safe group of mothers at your stage.": "आपके ही चरण की माँओं का एक छोटा, सुरक्षित समूह।",
  "Baby care": "शिशु की देखभाल", "Vaccines, growth, milestones, benefits.": "टीके, विकास, पड़ाव और लाभ।",
  "Invite family and choose what they see.": "परिवार को आमंत्रित करें और चुनें कि वे क्या देखें।",
  "Weekly report": "साप्ताहिक रिपोर्ट", "Your week, and a one-page summary for your doctor.": "आपका सप्ताह, और डॉक्टर के लिए एक पृष्ठ का सारांश।",
  "Privacy & safety": "गोपनीयता और सुरक्षा", "PIN lock, quick exit, consent controls.": "पिन लॉक, तुरंत बाहर निकलना, सहमति नियंत्रण।",
  "Family home": "परिवार का होम", "Learn, help, share night feeds.": "सीखें, मदद करें, रात के दूध पिलाने बाँटें।",
  "Professional dashboard": "विशेषज्ञ डैशबोर्ड", "Patients by urgency, callbacks, moderation.": "तात्कालिकता के अनुसार मरीज़, कॉलबैक, मॉडरेशन।",
  "ASHA dashboard": "आशा डैशबोर्ड", "Mothers in your area sorted by risk.": "आपके क्षेत्र की माँएँ, जोखिम के अनुसार क्रमबद्ध।",
  "Stretch": "अगला चरण", "MVP": "डेमो",
  "Live": "लाइव", "Family": "परिवार", "First 6 weeks": "पहले 6 सप्ताह", "EPDS": "ईपीडीएस", "Sample profiles": "नमूना प्रोफ़ाइल",

  // ---------- generic ----------
  "Yes": "हाँ", "No": "नहीं", "Back": "वापस", "Done": "हो गया", "Add": "जोड़ें", "Set": "सेट करें", "Call": "कॉल करें", "Book": "बुक करें",
  "Close": "बंद करें", "Leave": "छोड़ें", "Post": "पोस्ट करें", "Remove": "हटाएँ", "Sample": "नमूना", "h": "घं.", "kg": "किग्रा",
  "or": "या", "Hello": "नमस्ते", "none yet": "अभी कोई नहीं", "Family:": "परिवार:", "Planned next:": "आगे की योजना:",
  "AfterBloom offers screening support and care navigation, not a diagnosis. In an emergency call 112.": "आफ्टरब्लूम जाँच में सहायता और सही देखभाल तक पहुँचने में मार्गदर्शन देता है; यह रोग का निदान नहीं है। आपातकाल में 112 पर कॉल करें।",

  // ---------- levels ----------
  "RED": "लाल", "AMBER": "नारंगी", "GREEN": "हरा",
  "Go to hospital now": "तुरंत अस्पताल जाएँ", "See a doctor within 24 hours": "24 घंटे के भीतर डॉक्टर को दिखाएँ", "Normal recovery": "स्वास्थ्य लाभ सामान्य है",
  "low": "कम", "possible": "संभावित", "probable": "प्रबल संभावना", "Low": "कम", "Possible": "संभावित", "Probable": "प्रबल संभावना",
  "Medium": "मध्यम", "High": "उच्च",

  // ---------- crisis / lock ----------
  "This is an emergency. Call emergency services now.": "यह एक आपातकाल है। अभी आपातकालीन सेवा को कॉल करें।",
  "You are not alone. Help is available right now.": "आप अकेली नहीं हैं। मदद अभी उपलब्ध है।",
  "This needs care right now. Go to the nearest hospital.": "इसमें अभी इलाज की ज़रूरत है। निकटतम अस्पताल जाएँ।",
  "We noticed: {r}": "हमने यह देखा: {r}",
  "Call 112 (emergency)": "112 पर कॉल करें (आपातकाल)", "Call Tele-MANAS (free, 24x7)": "टेली-मानस को कॉल करें (मुफ़्त, 24x7)",
  "Stay with her. Do not leave her alone with the baby. Tell the doctors about the signs you saw.": "उनके साथ रहें। उन्हें बच्चे के साथ अकेला न छोड़ें। आपने जो संकेत देखे, वे डॉक्टरों को बताएँ।",
  "Find nearest hospital": "निकटतम अस्पताल खोजें",
  "Your emergency contact ({c}) has been alerted, as you agreed.": "आपकी सहमति के अनुसार आपके आपातकालीन संपर्क ({c}) को सूचित कर दिया गया है।",
  "Rohan (husband)": "रोहन (पति)",
  "Your care team has been flagged for an immediate callback. You can also talk to someone free right now on 14416.": "आपकी देखभाल टीम को तुरंत कॉल करने के लिए सूचित कर दिया गया है। आप अभी 14416 पर किसी से मुफ़्त बात भी कर सकती हैं।",
  "I am safe, close this screen": "मैं सुरक्षित हूँ, यह स्क्रीन बंद करें",
  "Enter your PIN": "अपना पिन दर्ज करें", "Wrong PIN": "गलत पिन", "Need help now? (no PIN needed)": "अभी मदद चाहिए? (पिन की ज़रूरत नहीं)",
  "Your answer to the last question": "आखिरी प्रश्न का आपका उत्तर", "Something you wrote in your circle": "आपने अपने सर्कल में जो लिखा",
  "Thoughts of self-harm": "खुद को नुकसान पहुँचाने के विचार", "Possible postpartum psychosis warning signs": "प्रसवोत्तर मनोविक्षिप्ति (साइकोसिस) के संभावित चेतावनी संकेत",
  "Family reported warning signs": "परिवार ने चेतावनी संकेत बताए",

  // ---------- triage result ----------
  "Based on:": "आधार:", "Call 112": "112 पर कॉल करें",
  "Please see your doctor or ANM within a day. Do not wait for it to pass.": "कृपया एक दिन के भीतर अपने डॉक्टर या एएनएम को दिखाएँ। अपने आप ठीक होने का इंतज़ार न करें।",
  "Book a session now": "अभी सत्र बुक करें",
  "This sounds like normal recovery. Rest, drink water, eat regularly.": "यह स्वास्थ्य लाभ की सामान्य प्रक्रिया लगती है। आराम करें, पानी पिएँ और नियमित खाना खाएँ।",
  "Watch for: heavy bleeding, fever, severe headache with blurred vision, chest pain, or feeling very low. If any appear, check again straight away.": "इन पर नज़र रखें: ज़्यादा खून बहना, बुखार, तेज़ सिरदर्द के साथ धुंधला दिखना, सीने में दर्द, या बहुत उदास महसूस करना। इनमें से कुछ भी हो तो तुरंत फिर से जाँच करें।",

  // ---------- home ----------
  "After the baby comes home,": "बच्चे के घर आने के बाद,", "we check on you.": "हम आपका हालचाल पूछते हैं।",
  "Day {n} after your {d}.": "आपके {d} के बाद दिन {n}।", "c-section": "सी-सेक्शन (ऑपरेशन)", "C-section": "सी-सेक्शन (ऑपरेशन)",
  "{b} is {w} weeks old.": "{b} {w} सप्ताह का है।",
  "See your trend": "अपना ट्रेंड देखें", "Do today's check-in": "आज का चेक-इन करें", "Is this normal?": "क्या यह सामान्य है?",
  "The Gap": "कमी", "Welcome to AfterBloom": "आफ्टरब्लूम में आपका स्वागत है",
  "Childbirth in India is now mostly safe inside the hospital, but the weeks after discharge are not. About a third of maternal deaths happen after the mother goes home, and depression often goes unseen. AfterBloom detects early and routes quickly into human care.": "भारत में अस्पताल के अंदर प्रसव अब ज़्यादातर सुरक्षित है, लेकिन छुट्टी के बाद के सप्ताह उतने सुरक्षित नहीं हैं। लगभग एक-तिहाई मातृ मृत्यु माँ के घर जाने के बाद होती हैं, और अवसाद अक्सर पहचाना ही नहीं जाता। आफ्टरब्लूम जल्दी पहचान करता है और तुरंत इंसानी देखभाल तक पहुँचाता है।",
  "mothers screen positive for PPD": "माँएँ प्रसवोत्तर अवसाद की जाँच में पॉज़िटिव आती हैं",
  "maternal deaths per 100,000 births": "प्रति 1,00,000 जीवित जन्मों पर मातृ मृत्यु",
  "of maternal deaths come after discharge": "मातृ मृत्यु अस्पताल से छुट्टी के बाद होती हैं",
  "with common mental disorders untreated": "सामान्य मानसिक विकार वालों को कोई इलाज नहीं मिलता",
  "Sources: Upadhyay et al. 2017; SRS 2022-24; NHM; NMHS 2015-16.": "स्रोत: उपाध्याय आदि 2017; एसआरएस 2022-24; एनएचएम; एनएमएचएस 2015-16।",
  "Our Care": "हमारी देखभाल", "We can help you heal": "हम आपके स्वस्थ होने में मदद कर सकते हैं",
  "Describe a symptom in English, Hindi or Hinglish and get a clear red, amber or green answer.": "अंग्रेज़ी, हिंदी या हिंग्लिश में कोई लक्षण बताइए और लाल, नारंगी या हरा, एक साफ़ जवाब पाइए।",
  "Mind check": "मन की जाँच", "A 2-minute wellness check at set times. Worrying results go to a person, never just a screen.": "तय समय पर 2 मिनट की स्वास्थ्य जाँच। चिंताजनक नतीजे किसी इंसान तक पहुँचते हैं, सिर्फ़ स्क्रीन पर नहीं दिखते।",
  "Talk to someone": "किसी से बात करें", "Video sessions with registered psychologists and psychiatrists. Free Tele-MANAS always beside them.": "पंजीकृत मनोवैज्ञानिकों और मनोचिकित्सकों के साथ वीडियो सत्र। मुफ़्त टेली-मानस हमेशा साथ में उपलब्ध।",
  "Family and circles": "परिवार और सर्कल", "Bring your family in, and meet mothers at your stage in a small, safe circle.": "अपने परिवार को जोड़ें और एक छोटे, सुरक्षित सर्कल में अपने ही चरण की माँओं से मिलें।",
  "Learn more": "और जानें", "Evidence": "प्रमाण", "Proving our expertise": "हमारी विशेषज्ञता के प्रमाण",
  "Built on a validated screening tool and on peer support that has been tested in India. The AI never writes advice; every message is prewritten and clinician-reviewed.": "यह एक प्रमाणित जाँच-पत्र और भारत में परखे गए सहकर्मी सहयोग पर आधारित है। एआई कभी सलाह नहीं लिखता; हर संदेश पहले से लिखा होता है और चिकित्सक द्वारा जाँचा गया होता है।",
  "EPDS sensitivity (Indian versions)": "ईपीडीएस संवेदनशीलता (भारतीय संस्करण)", "BMC Psychiatry, 2021": "बीएमसी साइकियाट्री, 2021",
  "EPDS specificity": "ईपीडीएस विशिष्टता", "Remission with peer support (Goa trial)": "सहकर्मी सहयोग से रोग-मुक्ति (गोवा परीक्षण)",
  "vs 60% in usual care. Fuhr et al., Lancet Psychiatry, 2019": "सामान्य देखभाल में 60% के मुकाबले। फुहर आदि, लैंसेट साइकियाट्री, 2019",
  "Try the mind check": "मन की जाँच आज़माएँ",
  "Small circles of 15 to 20 mothers at your stage, with crisis language routed to humans.": "आपके ही चरण की 15 से 20 माँओं के छोटे सर्कल, जिनमें संकट वाली भाषा इंसानों तक पहुँचाई जाती है।",
  "Crisis help is never gated": "संकट में मदद पर कोई रोक नहीं",
  "No login, no loading screen, no paywall. Tele-MANAS 14416 and 112 are one tap away.": "न लॉगिन, न लोडिंग स्क्रीन, न भुगतान की दीवार। टेली-मानस 14416 और 112 बस एक टैप दूर हैं।",
  "Dashboard": "डैशबोर्ड", "Your day, {name}": "{name}, आपका दिन", "Today for you": "आज आपके लिए", "Your week at a glance": "आपका सप्ताह एक नज़र में",
  "Mood": "मूड", "Appetite": "भूख", "Sleep": "नींद", "Check-ins": "चेक-इन",
  "Today's check-in done": "आज का चेक-इन हो गया", "Do today's 30-second check-in": "आज का 30 सेकंड का चेक-इन करें",
  "Mind check: {l}": "मन की जाँच: {l}", "Baby: {a} vaccines ({n})": "शिशु: {a} के टीके ({n})", "See your week": "अपना सप्ताह देखें",
  "Free help is always here:": "मुफ़्त मदद हमेशा उपलब्ध है:", "24×7, 20 languages": "24×7, 20 भाषाएँ", "Emergency": "आपातकाल",
  "Explore": "खोजें", "Everything in AfterBloom": "आफ्टरब्लूम में सब कुछ",
  "Week 2 (light check)": "सप्ताह 2 (हल्की जाँच)", "Week 6": "सप्ताह 6", "Month 3": "महीना 3", "Month 6": "महीना 6",

  // ---------- symptom checker ----------
  
  "Tell us what you feel in English, Hindi or Hinglish. We match your words to known symptoms. The advice is always pre-written and clinician-reviewed, never AI-written.": "आप जो महसूस कर रही हैं, वह अंग्रेज़ी, हिंदी या हिंग्लिश में बताइए। हम आपके शब्दों को जाने-पहचाने लक्षणों से मिलाते हैं। सलाह हमेशा पहले से लिखी और चिकित्सक द्वारा जाँची हुई होती है, एआई द्वारा लिखी नहीं।",
  "Voice input is not supported in this browser. Please type.": "इस ब्राउज़र में आवाज़ से लिखना उपलब्ध नहीं है। कृपया टाइप करें।",
  "For me": "मेरे लिए", "For my baby": "मेरे बच्चे के लिए",
  "e.g. I have fever and my stitches are hurting a lot": "जैसे: मुझे बुखार है और टाँकों में बहुत दर्द हो रहा है", "e.g. baby not feeding well": "जैसे: बच्चा ठीक से दूध नहीं पी रहा",
  "Check": "जाँचें", "Listening…": "सुन रहे हैं…", "Speak": "बोलें",
  "Did you mean…?": "क्या आपका मतलब यह था…?", "None of these": "इनमें से कोई नहीं",
  "We could not match this to a known symptom, and we never guess.": "हम इसे किसी जाने-पहचाने लक्षण से नहीं मिला सके, और हम कभी अंदाज़ा नहीं लगाते।",
  "Please speak to a doctor about this.": "कृपया इस बारे में डॉक्टर से बात करें।", "Book a session": "सत्र बुक करें",
  "Or pick from the list": "या सूची में से चुनें",
  "Mind warning signs: you or your family can tap": "मन के चेतावनी संकेत: आप या आपका परिवार टैप कर सकता है",
  "If any of these apply, tap it. We will tell you what to do right away.": "इनमें से कोई भी लागू हो तो उस पर टैप करें। हम तुरंत बताएँगे कि क्या करना है।",
  "Confusion or seeming 'not herself'": "भ्रम की स्थिति, या ऐसा लगना कि वे \"अपने जैसी नहीं रहीं\"",
  "Seeing or hearing things others don't": "ऐसी चीज़ें दिखना या सुनाई देना जो दूसरों को नहीं दिखतीं या सुनाई देतीं",
  "Believing the baby is in danger or 'not hers'": "यह मानना कि बच्चा ख़तरे में है या \"उसका अपना नहीं है\"",
  "Not sleeping for days without feeling tired": "थकान महसूस किए बिना कई दिनों तक न सोना",

  // ---------- daily check-in ----------
  "30 seconds. Tap, don't type.": "30 सेकंड। टैप करें, टाइप नहीं।",
  "How is your mood?": "आपका मूड कैसा है?", "How is your appetite?": "आपकी भूख कैसी है?", "How many hours did you sleep (in total)?": "आप कुल कितने घंटे सोईं?",
  "Danger signs today": "आज के ख़तरे के संकेत", "Soaking a pad in an hour, or large clots?": "एक घंटे में पैड भीग गया, या खून के बड़े थक्के?",
  "Fever (above 100.4°F / 38°C)?": "बुखार (100.4°F / 38°C से ऊपर)?", "Headache?": "सिरदर्द?", "Yes, with blurred vision": "हाँ, धुंधला दिखने के साथ",
  "Wound red, swollen or leaking?": "घाव लाल, सूजा हुआ या उससे रिसाव हो रहा है?", "Chest pain or trouble breathing?": "सीने में दर्द या साँस लेने में तकलीफ़?",
  "Log a home blood pressure reading?": "घर पर नापा गया ब्लड प्रेशर दर्ज करें?", "Upper (e.g. 120)": "ऊपर वाला (जैसे 120)", "Lower (e.g. 80)": "नीचे वाला (जैसे 80)",
  "Save today's check-in": "आज का चेक-इन सेव करें", "Thank you for checking in 💜 Everything looks fine today.": "चेक-इन करने के लिए धन्यवाद 💜 आज सब कुछ ठीक लग रहा है।",
  "Your trend": "आपका ट्रेंड", "A trend over two weeks tells more than a single bad day. With your consent, your professional sees this chart between sessions.": "दो सप्ताह का ट्रेंड किसी एक ख़राब दिन से कहीं ज़्यादा बताता है। आपकी सहमति से, आपके विशेषज्ञ सत्रों के बीच यह चार्ट देख सकते हैं।",
  "Blood pressure": "ब्लड प्रेशर", "No check-ins yet.": "अभी तक कोई चेक-इन नहीं।", "Sleep (h)": "नींद (घं.)", "Upper": "ऊपर वाला", "Lower": "नीचे वाला",
  
  "Heavy bleeding or large clots": "बहुत ज़्यादा खून बहना या खून के बड़े थक्के", "Chest pain or trouble breathing": "सीने में दर्द या साँस लेने में तकलीफ़",
  "Headache with vision changes": "सिरदर्द के साथ नज़र में बदलाव", "Fever": "बुखार", "Headache": "सिरदर्द", "Wound redness or discharge": "घाव में लालिमा या रिसाव",
  "Heavy bleeding": "बहुत ज़्यादा खून बहना", "Fits or fainting": "दौरे या बेहोशी", "Severe headache with blurred vision": "तेज़ सिरदर्द के साथ धुंधला दिखना",
  "Chest pain or breathlessness": "सीने में दर्द या साँस फूलना", "Fever with chills or foul-smelling discharge": "ठंड लगने के साथ बुखार या बदबूदार स्राव",
  "Painful swollen calf": "पिंडली में दर्द और सूजन", "Danger sign in the baby": "बच्चे में ख़तरे का संकेत",

  // ---------- mind check ----------
  "A routine wellness check we offer every new mother. It takes 2 minutes.": "यह एक नियमित स्वास्थ्य जाँच है जो हम हर नई माँ को देते हैं। इसमें 2 मिनट लगते हैं।",
  "Feeling low, worried or overwhelmed after birth is very common, and it is treatable. These 10 questions help your care team support you. There are no right or wrong answers.": "प्रसव के बाद उदास, चिंतित या बोझिल महसूस करना बहुत आम है, और इसका इलाज संभव है। ये 10 प्रश्न आपकी देखभाल टीम को आपकी मदद करने में सहायता देते हैं। कोई उत्तर सही या गलत नहीं है।",
  "Think about how you have felt": "सोचिए कि आपने कैसा महसूस किया है", "in the past 7 days": "पिछले 7 दिनों में", ", not just today.": ", सिर्फ़ आज नहीं।",
  "Start (2 minutes)": "शुरू करें (2 मिनट)", "When we offer it": "हम यह कब देते हैं", "due now": "अभी देय", "in {n} days": "{n} दिन में",
  "Your past checks": "आपकी पिछली जाँचें", "Doing well": "सब ठीक चल रहा है", "Your care team is in touch": "आपकी देखभाल टीम संपर्क में है",
  "Edinburgh Postnatal Depression Scale (Cox, Holden & Sagovsky, 1987). Hindi wording: translation pending clinician review.": "एडिनबरा प्रसवोत्तर अवसाद स्केल (कॉक्स, होल्डन और सागोव्स्की, 1987)। हिंदी शब्दावली: अनुवाद चिकित्सक की समीक्षा के लिए लंबित है।",
  "Free help any time: Tele-MANAS 14416 (24×7). This check is screening support, not a diagnosis.": "किसी भी समय मुफ़्त मदद: टेली-मानस 14416 (24×7)। यह जाँच केवल एक प्रारंभिक सहायता है, रोग का निदान नहीं।",
  "Question {a} of {b}": "प्रश्न {a} / {b}",
  "Thank you 💜": "धन्यवाद 💜", "You seem to be coping well right now. Keep talking, keep resting, and keep checking in. We will remind you before your next check.": "अभी आप अच्छी तरह सँभल रही हैं। बात करती रहें, आराम करती रहें और चेक-इन करती रहें। अगली जाँच से पहले हम आपको याद दिलाएँगे।",
  "Thank you for sharing 💜": "बताने के लिए धन्यवाद 💜", "Many mothers feel this way, and support makes a real difference. We suggest talking to a counsellor, and we will offer this check again in 2 weeks.": "कई माँएँ ऐसा ही महसूस करती हैं, और सहारा सचमुच फ़र्क़ डालता है। हम सुझाव देते हैं कि आप किसी काउंसलर से बात करें, और हम यह जाँच 2 सप्ताह बाद फिर से देंगे।",
  "Talk to a counsellor": "काउंसलर से बात करें", "Our care team will be in touch.": "हमारी देखभाल टीम आपसे संपर्क करेगी।",
  "Your psychologist will call you within 24 to 48 hours to talk it through. You do not need to do anything else.": "आपके मनोवैज्ञानिक 24 से 48 घंटे के भीतर आपको कॉल करके बात करेंगे। आपको और कुछ करने की ज़रूरत नहीं है।",
  "Want to talk sooner?": "जल्दी बात करना चाहती हैं?", "free, 24×7, 20 languages.": "मुफ़्त, 24×7, 20 भाषाएँ।",
  "EPDS question 10 positive: thoughts of self-harm": "ईपीडीएस प्रश्न 10 सकारात्मक: खुद को नुकसान पहुँचाने के विचार",
  "I have been able to laugh and see the funny side of things": "मैं हँस पाई हूँ और चीज़ों का मज़ेदार पहलू देख पाई हूँ",
  "As much as I always could": "जितना मैं हमेशा कर पाती थी", "Not quite so much now": "अब उतना नहीं", "Definitely not so much now": "अब निश्चित रूप से उतना नहीं", "Not at all": "बिल्कुल नहीं",
  "I have looked forward with enjoyment to things": "मैं आनंद के साथ आने वाली बातों की प्रतीक्षा करती रही हूँ",
  "As much as I ever did": "जितना मैं हमेशा करती थी", "Rather less than I used to": "पहले से कुछ कम", "Definitely less than I used to": "पहले से निश्चित रूप से कम", "Hardly at all": "लगभग बिल्कुल नहीं",
  "I have blamed myself unnecessarily when things went wrong": "जब कुछ गलत हुआ तो मैंने बिना वजह खुद को दोषी ठहराया है",
  "Yes, most of the time": "हाँ, ज़्यादातर समय", "Yes, some of the time": "हाँ, कभी-कभी", "Not very often": "बहुत बार नहीं", "No, never": "नहीं, कभी नहीं",
  "I have been anxious or worried for no good reason": "मैं बिना किसी ठोस कारण के चिंतित या परेशान रही हूँ",
  "No, not at all": "नहीं, बिल्कुल नहीं", "Hardly ever": "लगभग कभी नहीं", "Yes, sometimes": "हाँ, कभी-कभी", "Yes, very often": "हाँ, बहुत बार",
  "I have felt scared or panicky for no very good reason": "मैं बिना किसी ठोस कारण के डरी हुई या घबराई हुई महसूस करती रही हूँ",
  "Yes, quite a lot": "हाँ, काफ़ी ज़्यादा", "No, not much": "नहीं, ज़्यादा नहीं",
  "Things have been getting on top of me": "चीज़ें मुझ पर भारी पड़ती जा रही हैं",
  "Yes, most of the time I haven't been able to cope at all": "हाँ, ज़्यादातर समय मैं बिल्कुल सँभल नहीं पाई हूँ",
  "Yes, sometimes I haven't been coping as well as usual": "हाँ, कभी-कभी मैं पहले की तरह नहीं सँभल पाई हूँ",
  "No, most of the time I have coped quite well": "नहीं, ज़्यादातर समय मैं काफ़ी अच्छी तरह सँभली हूँ",
  "No, I have been coping as well as ever": "नहीं, मैं हमेशा की तरह अच्छी तरह सँभल रही हूँ",
  "I have been so unhappy that I have had difficulty sleeping": "मैं इतनी दुखी रही हूँ कि मुझे सोने में कठिनाई हुई है",
  "I have felt sad or miserable": "मैंने उदास या बहुत दुखी महसूस किया है", "Yes, quite often": "हाँ, काफ़ी बार",
  "I have been so unhappy that I have been crying": "मैं इतनी दुखी रही हूँ कि मैं रोती रही हूँ", "Only occasionally": "केवल कभी-कभार",
  "The thought of harming myself has occurred to me": "खुद को नुकसान पहुँचाने का विचार मेरे मन में आया है",
  "Sometimes": "कभी-कभी", "Never": "कभी नहीं",

  // ---------- care ----------
  "Video sessions inside the app. Cost should never block help.": "ऐप के भीतर वीडियो सत्र। खर्च कभी मदद के आड़े नहीं आना चाहिए।",
  "Free: Tele-MANAS 14416": "मुफ़्त: टेली-मानस 14416", "Government mental health helpline. 24×7, 20 languages, no cost, no booking.": "सरकारी मानसिक स्वास्थ्य हेल्पलाइन। 24×7, 20 भाषाएँ, कोई शुल्क नहीं, बुकिंग की ज़रूरत नहीं।",
  "Your sessions": "आपके सत्र", "Join video": "वीडियो से जुड़ें", "Speaks:": "भाषाएँ:", "/ session": "/ सत्र",
  "Psychologists and counsellors provide talk therapy. A psychiatrist is for diagnosis and medication decisions. In this demo, professionals are clearly labelled sample profiles; real onboarding needs a hospital or clinical partner.": "मनोवैज्ञानिक और काउंसलर बातचीत से उपचार (टॉक थेरेपी) देते हैं। मनोचिकित्सक निदान और दवा संबंधी निर्णयों के लिए हैं। इस डेमो में विशेषज्ञों को स्पष्ट रूप से नमूना प्रोफ़ाइल बताया गया है; असली जुड़ाव के लिए किसी अस्पताल या चिकित्सा भागीदार की ज़रूरत है।",
  "Choose a time with {name}": "{name} के साथ समय चुनें", "Video session": "वीडियो सत्र",
  "Clinical psychologist": "क्लिनिकल मनोवैज्ञानिक", "Counsellor": "काउंसलर", "Psychiatrist": "मनोचिकित्सक",
  "M.Phil. Clinical Psychology": "एम.फिल. क्लिनिकल साइकोलॉजी", "M.A. Counselling Psychology": "एम.ए. काउंसलिंग साइकोलॉजी", "MD Psychiatry": "एमडी मनोचिकित्सा",
  "RCI CRR No. A12345 (sample)": "आरसीआई सीआरआर संख्या A12345 (नमूना)", "RCI CRR No. A67890 (sample)": "आरसीआई सीआरआर संख्या A67890 (नमूना)", "Medical Council Reg. No. 54321 (sample)": "मेडिकल काउंसिल पंजीकरण संख्या 54321 (नमूना)",
  "Talk therapy for postpartum low mood and anxiety": "प्रसव के बाद उदासी और चिंता के लिए टॉक थेरेपी", "Supportive counselling, sleep and adjustment": "सहयोगी परामर्श, नींद और नई स्थिति से तालमेल", "Diagnosis and medication decisions": "निदान और दवा संबंधी निर्णय",
  "English": "अंग्रेज़ी", "Hindi": "हिंदी", "Marathi": "मराठी",
  "Today 6:00 PM": "आज शाम 6:00 बजे", "Today 8:00 PM": "आज रात 8:00 बजे", "Tomorrow 10:00 AM": "कल सुबह 10:00 बजे", "Tomorrow 4:30 PM": "कल शाम 4:30 बजे", "Day after 11:00 AM": "परसों सुबह 11:00 बजे",

  // ---------- family circle (mother) ----------
  "Support from family is the strongest protection for a new mother. You choose who joins and what each person sees.": "परिवार का सहारा एक नई माँ की सबसे बड़ी सुरक्षा है। कौन जुड़ेगा और हर व्यक्ति क्या देखेगा, यह आप तय करती हैं।",
  "Invite someone": "किसी को आमंत्रित करें", "Name": "नाम", "Send invite (WhatsApp link)": "आमंत्रण भेजें (व्हाट्सऐप लिंक)",
  "Husband / partner": "पति / साथी", "My mother": "मेरी माँ", "Mother-in-law": "सास", "Other": "अन्य", "Husband": "पति",
  "Safety alerts": "सुरक्षा अलर्ट", "RED symptoms and missed check-ins": "लाल लक्षण और छूटे हुए चेक-इन",
  "Mood and sleep trends": "मूड और नींद के ट्रेंड", "Weekly \"how to help\" note": "साप्ताहिक \"कैसे मदद करें\" नोट", "No scores or health details": "कोई स्कोर या स्वास्थ्य संबंधी जानकारी नहीं",
  "Alert my emergency contact on a RED result": "लाल नतीजे पर मेरे आपातकालीन संपर्क को सूचित करें",
  "Currently: {c}. Only if you agree in advance.": "अभी: {c}। केवल तभी जब आप पहले से सहमत हों।",
  "Night-feed planner": "रात में दूध पिलाने की योजना", "Alerts sent to family": "परिवार को भेजे गए अलर्ट",
  "Tap a slot to take that night feed (tap again to give it back). Empty slots are covered by {name}.": "रात के दूध पिलाने की ज़िम्मेदारी लेने के लिए किसी समय-स्लॉट पर टैप करें (वापस देने के लिए फिर टैप करें)। खाली स्लॉट {name} सँभालती हैं।",
  "Mon": "सोम", "Tue": "मंगल", "Wed": "बुध", "Thu": "गुरु", "Fri": "शुक्र", "Sat": "शनि", "Sun": "रवि",
  "10 PM - 12 AM": "रात 10 - 12 बजे", "12 AM - 2 AM": "रात 12 - 2 बजे", "2 AM - 4 AM": "रात 2 - 4 बजे", "4 AM - 6 AM": "सुबह 4 - 6 बजे",
  "She slept under 5 hours on {n} nights this week. Can someone take a night feed?": "इस सप्ताह वे {n} रातें 5 घंटे से कम सोईं। क्या कोई रात में दूध पिलाने की ज़िम्मेदारी ले सकता है?",
  "Ask her what would help most today, then do it without being asked twice.": "उनसे पूछिए कि आज सबसे ज़्यादा किस चीज़ से मदद मिलेगी, फिर उसे दोबारा कहे बिना कीजिए।",
  "Cook a meal or fill her water bottle - small things lift a very big load.": "खाना बना दीजिए या उनकी पानी की बोतल भर दीजिए - छोटी बातें बहुत बड़ा बोझ हल्का कर देती हैं।",
  "Listen without fixing. 'That sounds hard' is a good sentence.": "हल निकालने की कोशिश किए बिना सुनिए। \"यह तो मुश्किल लग रहा है\" एक अच्छा वाक्य है।",

  // ---------- family home ----------
  "Supporting {name}": "{name} का साथ दें", "Hello {me}. Here is how to help {name} and {baby}.": "नमस्ते {me}। {name} और {baby} की मदद करने का तरीका यह है।",
  "Learn": "सीखें", "What I noticed": "मैंने क्या देखा", "Night feeds": "रात के दूध", "Alerts": "अलर्ट", "Alerts ({n})": "अलर्ट ({n})", "How to help": "मदद कैसे करें",
  "What postpartum depression actually is (2 min)": "प्रसवोत्तर अवसाद असल में क्या है (2 मिनट)",
  "Postpartum depression (PPD) is a medical condition, not weakness and not a lack of gratitude. About 1 in 5 Indian mothers has it.": "प्रसवोत्तर अवसाद (पीपीडी) एक चिकित्सीय स्थिति है; यह कमज़ोरी नहीं है और कृतज्ञता की कमी भी नहीं है। लगभग 5 में से 1 भारतीय माँ को यह होता है।",
  "It can show up as constant sadness, crying, not sleeping even when the baby sleeps, not eating, feeling like a bad mother, or not feeling close to the baby.": "यह लगातार उदासी, रोना, बच्चे के सोने पर भी नींद न आना, खाना न खाना, खुद को बुरी माँ समझना, या बच्चे से लगाव महसूस न होने के रूप में दिख सकता है।",
  "It is very treatable, especially when the family supports her. Saying 'you have a healthy baby, why are you sad?' makes it worse.": "इसका इलाज बहुत संभव है, ख़ासकर जब परिवार साथ दे। \"तुम्हारा बच्चा स्वस्थ है, फिर उदास क्यों हो?\" कहने से हालत और बिगड़ती है।",
  "What is normal after birth": "प्रसव के बाद क्या सामान्य है",
  "Bleeding for up to 6 weeks that slowly gets lighter, cramps in the first week, tiredness, and tearfulness in the first two weeks (baby blues) are normal.": "6 सप्ताह तक खून आना जो धीरे-धीरे हल्का होता जाए, पहले सप्ताह में ऐंठन, थकान, और पहले दो सप्ताह में आँसू आना (बेबी ब्लूज़) सामान्य है।",
  "Baby blues should fade within about 2 weeks. If sadness stays or gets worse, it may be more than the blues.": "बेबी ब्लूज़ लगभग 2 सप्ताह में कम हो जाने चाहिए। अगर उदासी बनी रहे या बढ़े, तो यह बेबी ब्लूज़ से ज़्यादा हो सकता है।",
  "Warning signs to watch for": "इन चेतावनी संकेतों पर नज़र रखें",
  "Go to hospital now: heavy bleeding, fits, severe headache with blurred vision, chest pain, fever with chills or foul-smelling discharge, a painful swollen calf, or any thought of harming herself or the baby.": "तुरंत अस्पताल जाएँ: बहुत ज़्यादा खून बहना, दौरे पड़ना, तेज़ सिरदर्द के साथ धुंधला दिखना, सीने में दर्द, ठंड लगने के साथ बुखार या बदबूदार स्राव, पिंडली में दर्द और सूजन, या खुद को या बच्चे को नुकसान पहुँचाने का कोई भी विचार।",
  "Call emergency services at once if she is confused, sees or hears things others do not, believes the baby is in danger or not hers, or has not slept for days.": "अगर वे भ्रमित हैं, ऐसी चीज़ें देखती या सुनती हैं जो दूसरों को नहीं दिखतीं, मानती हैं कि बच्चा ख़तरे में है या उनका नहीं है, या कई दिनों से सोई नहीं हैं, तो तुरंत आपातकालीन सेवा को कॉल करें।",
  "How to help without taking over": "बिना हावी हुए मदद कैसे करें",
  "Ask what would help, then do it. Take night feeds so she can sleep a full 4 to 5 hours in a row.": "पूछिए कि किस चीज़ से मदद मिलेगी, फिर वह कीजिए। रात के दूध पिलाने की ज़िम्मेदारी लीजिए ताकि वे लगातार पूरे 4 से 5 घंटे सो सकें।",
  "Do not give advice or compare. Listen. Say: 'I am here. You are doing well.'": "सलाह न दें और तुलना न करें। सुनिए। कहिए: \"मैं यहाँ हूँ। तुम अच्छा कर रही हो।\"",
  "Protect her from visitors and comments. Handle food, water and housework without being asked.": "उन्हें मेहमानों और तानों से बचाइए। खाना, पानी और घर के काम बिना कहे सँभालिए।",
  "Encourage her to talk to a counsellor. It is a sign of strength.": "उन्हें काउंसलर से बात करने के लिए प्रोत्साहित कीजिए। यह ताकत की निशानी है।",
  "Emergency signs (postpartum psychosis):": "आपातकालीन संकेत (प्रसवोत्तर मनोविक्षिप्ति):", "I see these signs": "मुझे ये संकेत दिख रहे हैं",
  "Mothers often under-report. In the last 2 weeks, have you noticed:": "माँएँ अक्सर अपनी तकलीफ़ कम बताती हैं। पिछले 2 सप्ताह में क्या आपने देखा है:",
  "Is she sleeping less than usual, even when the baby sleeps?": "क्या बच्चे के सोने पर भी वे सामान्य से कम सो रही हैं?",
  "Is she eating much less (or much more) than usual?": "क्या वे सामान्य से बहुत कम (या बहुत ज़्यादा) खा रही हैं?",
  "Does she seem withdrawn, quiet, or avoid people?": "क्या वे अलग-थलग, चुप या लोगों से बचती हुई लगती हैं?",
  "Does she cry often or seem hopeless?": "क्या वे अक्सर रोती हैं या निराश लगती हैं?",
  "Does she seem uninterested in or worried about bonding with the baby?": "क्या उन्हें बच्चे से जुड़ाव में रुचि नहीं है, या वे इसे लेकर चिंतित लगती हैं?",
  "Does she seem very anxious, irritable or panicky?": "क्या वे बहुत चिंतित, चिड़चिड़ी या घबराई हुई लगती हैं?",
  "Share with her care team": "उनकी देखभाल टीम के साथ साझा करें", "Thank you.": "धन्यवाद।", "Her care team will be told.": "उनकी देखभाल टीम को बताया जाएगा।",
  "Gentle next step: tell her you are there, and offer to sit with her while she talks to someone.": "अगला कोमल कदम: उन्हें बताइए कि आप साथ हैं, और जब वे किसी से बात करें तो साथ बैठने की पेशकश कीजिए।",
  "No alerts. You only see what {name} has agreed to share.": "कोई अलर्ट नहीं। आप केवल वही देखते हैं जो {name} ने साझा करने की सहमति दी है।",
  "Safety alert": "सुरक्षा अलर्ट", "How to help this week": "इस सप्ताह कैसे मदद करें",
  "{name} has not turned this note on. This is a preview of what it would look like; it never contains scores or health details.": "{name} ने यह नोट चालू नहीं किया है। यह उसका एक नमूना है कि वह कैसा दिखेगा; इसमें कभी स्कोर या स्वास्थ्य संबंधी जानकारी नहीं होती।",
  "See {baby}'s vaccine schedule": "{baby} का टीकाकरण कार्यक्रम देखें",

  // ---------- baby ----------
  "{baby}'s care": "{baby} की देखभाल", "Born {d} · {n} days old": "जन्म {d} · {n} दिन का",
  "Vaccines": "टीके", "Growth (next)": "विकास (आगे)", "Milestones (next)": "पड़ाव (आगे)", "Benefits (next)": "लाभ (आगे)",
  "Overdue by {n} days": "{n} दिन की देरी", "Due today": "आज देय", "Due in {n} days": "{n} दिन में देय", "Mark done": "हो गया चिह्नित करें",
  "Birth": "जन्म", "6 weeks": "6 सप्ताह", "10 weeks": "10 सप्ताह", "14 weeks": "14 सप्ताह", "9-12 months": "9-12 महीने", "16-24 months": "16-24 महीने",
  "Hepatitis B birth dose": "हेपेटाइटिस बी जन्म खुराक", "JE-1 (endemic districts)": "जेई-1 (प्रभावित ज़िले)", "PCV booster": "पीसीवी बूस्टर", "Vitamin A": "विटामिन ए", "DPT booster-1": "डीपीटी बूस्टर-1", "OPV booster": "ओपीवी बूस्टर",
  "National Immunization Schedule (MoHFW). Last verified:": "राष्ट्रीय टीकाकरण कार्यक्रम (स्वास्थ्य मंत्रालय)। अंतिम सत्यापन:",
  "Not yet verified - check MoHFW before demo": "अभी सत्यापित नहीं - डेमो से पहले स्वास्थ्य मंत्रालय के दस्तावेज़ से मिलान करें",
  "Confirm with your ANM or paediatrician.": "अपनी एएनएम या बाल रोग विशेषज्ञ से पुष्टि करें।",
  "Log {baby}'s weight. The chart shows the trend only; it never says \"malnourished\". That is a doctor's judgement.": "{baby} का वज़न दर्ज करें। चार्ट केवल ट्रेंड दिखाता है; यह कभी \"कुपोषित\" नहीं कहता। यह डॉक्टर का निर्णय है।",
  "Weight in kg, e.g. 3.4": "वज़न किग्रा में, जैसे 3.4",
  "Plot against the WHO Child Growth Standards curves, with length and head size.": "डब्ल्यूएचओ बाल विकास मानकों के वक्रों के साथ तुलना, लंबाई और सिर के आकार सहित।",
  "2 months": "2 महीने", "4 months": "4 महीने", "6 months": "6 महीने", "9 months": "9 महीने",
  "Smiles at people": "लोगों को देखकर मुस्कुराता है", "Follows things with eyes": "आँखों से चीज़ों का पीछा करता है", "Briefly calms when comforted": "गोद में लेने पर थोड़ी देर के लिए शांत हो जाता है",
  "Holds head steady": "सिर सीधा रखता है", "Coos and makes sounds": "गुनगुनाता और आवाज़ें निकालता है", "Reaches for toys": "खिलौनों की ओर हाथ बढ़ाता है",
  "Rolls over": "करवट लेता है", "Responds to own name": "अपने नाम पर प्रतिक्रिया देता है", "Passes things hand to hand": "चीज़ें एक हाथ से दूसरे हाथ में लेता है",
  "Sits without support": "बिना सहारे बैठता है", "Babbles 'mama' 'baba'": "\"मम्मा\" \"बाबा\" जैसी आवाज़ें निकालता है", "Plays peek-a-boo": "छुपन-छुपाई (पीक-ए-बू) खेलता है",
  "Full checklist from WHO or the Indian Academy of Pediatrics, reviewed by a paediatrician. Always talk to your doctor if you are worried.": "डब्ल्यूएचओ या इंडियन अकादमी ऑफ़ पीडियाट्रिक्स की पूरी चेकलिस्ट, जिसे बाल रोग विशेषज्ञ ने जाँचा हो। चिंता हो तो हमेशा अपने डॉक्टर से बात करें।",
  "PMMVY maternity benefit": "पीएमएमवीवाई मातृत्व लाभ",
  "For a first child, the government scheme pays ₹5,000 in two instalments. One is linked to the baby's 14-week vaccinations.": "पहले बच्चे के लिए यह सरकारी योजना ₹5,000 दो किस्तों में देती है। एक किस्त बच्चे के 14 सप्ताह के टीकों से जुड़ी है।",
  "Instalment 1: register the pregnancy and get a health check": "पहली किस्त: गर्भावस्था का पंजीकरण और स्वास्थ्य जाँच",
  "Instalment 2: birth registered + first cycle of vaccines (up to 14 weeks)": "दूसरी किस्त: जन्म पंजीकरण + टीकों का पहला चक्र (14 सप्ताह तक)",
  "Check eligibility and exact steps with your ANM or Anganwadi. Rules may change.": "पात्रता और सही प्रक्रिया अपनी एएनएम या आँगनवाड़ी से पूछें। नियम बदल सकते हैं।",

  // ---------- circles ----------
  "Bloom Circle": "ब्लूम सर्कल", "A small, safe group of mothers at the same stage as you.": "आपके ही चरण की माँओं का एक छोटा, सुरक्षित समूह।",
  "A small, safe group of mothers at the same stage as you": "आपके ही चरण की माँओं का एक छोटा, सुरक्षित समूह",
  "Your circle": "आपका सर्कल", "Hindi / English · babies born this month · about 18 mothers": "हिंदी / अंग्रेज़ी · इसी महीने जन्मे बच्चे · लगभग 18 माँएँ",
  "Community rules": "समुदाय के नियम", "No medical advice from members.": "सदस्यों से कोई चिकित्सीय सलाह नहीं।",
  "Please check anything medical with your doctor or the symptom checker. Unsafe advice spreads fast.": "चिकित्सा से जुड़ी कोई भी बात अपने डॉक्टर या लक्षण जाँच से पूछें। असुरक्षित सलाह बहुत तेज़ी से फैलती है।",
  "No judging, shaming or comparing (\"my baby already does this, does yours?\").": "कोई आलोचना, शर्मिंदा करना या तुलना नहीं (\"मेरा बच्चा तो यह पहले से करता है, आपका?\")।",
  "You can post anonymously. Your family cannot see your circle posts.": "आप गुमनाम रूप से पोस्ट कर सकती हैं। आपका परिवार आपके सर्कल की पोस्ट नहीं देख सकता।",
  "If someone writes about harming themselves, a human moderator is alerted and they are shown crisis help. The software never replies on its own.": "अगर कोई खुद को नुकसान पहुँचाने के बारे में लिखे, तो एक इंसानी मॉडरेटर को सूचित किया जाता है और उन्हें संकट में मदद की स्क्रीन दिखाई जाती है। सॉफ़्टवेयर कभी अपने आप जवाब नहीं देता।",
  "I agree, join my circle": "मैं सहमत हूँ, मेरे सर्कल में शामिल करें",
  "{city} · Hindi / English · 18 mothers · guided by a Bloom Buddy": "{city} · हिंदी / अंग्रेज़ी · 18 माँएँ · एक ब्लूम बडी के मार्गदर्शन में",
  "All": "सभी", "Feeding": "स्तनपान/आहार", "C-section recovery": "सी-सेक्शन के बाद स्वास्थ्य लाभ", "Body changes": "शरीर में बदलाव", "In-law pressure": "ससुराल का दबाव", "Returning to work": "काम पर लौटना", "Welcome": "स्वागत",
  "No posts here yet. Start the conversation.": "यहाँ अभी कोई पोस्ट नहीं है। बातचीत शुरू कीजिए।",
  "Anonymous mother": "गुमनाम माँ",
  "Week 2 and I feel like I have forgotten what sleep is. Anyone else?": "दूसरा सप्ताह है और ऐसा लगता है जैसे मैं भूल ही गई हूँ कि नींद क्या होती है। क्या और कोई भी ऐसा महसूस कर रही है?",
  "Welcome mothers 💜 This is your safe corner. You are not alone in how you feel.": "सभी माँओं का स्वागत है 💜 यह आपकी सुरक्षित जगह है। आप जो महसूस कर रही हैं, उसमें आप अकेली नहीं हैं।",
  "My mother-in-law keeps saying I should not feel sad because I have a healthy baby. It hurts.": "मेरी सास बार-बार कहती हैं कि मुझे उदास नहीं होना चाहिए क्योंकि मेरा बच्चा स्वस्थ है। इससे बहुत दुख होता है।",
  "Please check this with your doctor or use the symptom checker.": "कृपया यह अपने डॉक्टर से पूछें या लक्षण जाँच का उपयोग करें।",
  "Share with your circle…": "अपने सर्कल के साथ साझा करें…", "Post anonymously": "गुमनाम रूप से पोस्ट करें",
  "Bloom Buddies": "ब्लूम बडीज़", "Trained peer mentors who went through it themselves.": "प्रशिक्षित सहकर्मी मार्गदर्शक जो खुद इस दौर से गुज़र चुकी हैं।",
  "Needs trained people or an NGO partner.": "इसके लिए प्रशिक्षित लोगों या किसी एनजीओ भागीदार की ज़रूरत है।",
  "Monthly expert Q&A": "मासिक विशेषज्ञ प्रश्नोत्तर", "Live session with a psychologist, lactation consultant or gynaecologist.": "मनोवैज्ञानिक, स्तनपान सलाहकार या स्त्री रोग विशेषज्ञ के साथ लाइव सत्र।",
  "Production plan. Demo does not claim 24×7 moderation.": "यह उत्पादन की योजना है। डेमो 24×7 मॉडरेशन का दावा नहीं करता।",
  "Self-harm / crisis language": "खुद को नुकसान / संकट वाली भाषा", "Self-harm language in Bloom Circle": "ब्लूम सर्कल में खुद को नुकसान पहुँचाने वाली भाषा",

  // ---------- weekly report ----------
  "Every Sunday. The same data, written for three readers.": "हर रविवार। वही जानकारी, तीन पाठकों के लिए लिखी गई।",
  "Your week": "आपका सप्ताह", "For your doctor": "आपके डॉक्टर के लिए", "For family": "परिवार के लिए",
  "Your week 💜": "आपका सप्ताह 💜", "You checked in on": "आपने चेक-इन किया", "{n} of 7": "7 में से {n}", "days this week. Thank you for looking after yourself.": "दिन इस सप्ताह। अपना ध्यान रखने के लिए धन्यवाद।",
  "Symptoms you reported": "आपके बताए गए लक्षण", "None this week.": "इस सप्ताह कोई नहीं।", "Your care team is keeping an eye on this.": "आपकी देखभाल टीम इस पर नज़र रखे हुए है।",
  "Coming up": "आगे आने वाला", "Baby's next vaccine:": "शिशु का अगला टीका:", "{a} ({n} days)": "{a} ({n} दिन में)", "all done for now": "अभी के लिए सब पूरा",
  "Appointment:": "अपॉइंटमेंट:", "none booked": "कोई बुक नहीं", "This week's guidance": "इस सप्ताह का मार्गदर्शन",
  "No scores, no grades. Written from fixed templates, not AI.": "कोई स्कोर या ग्रेड नहीं। निश्चित टेम्पलेट से लिखा गया, एआई से नहीं।",
  "Download PDF": "पीडीएफ़ डाउनलोड करें", "Share on WhatsApp": "व्हाट्सऐप पर साझा करें",
  "AfterBloom clinical summary": "आफ्टरब्लूम चिकित्सकीय सारांश", "day {n} postpartum": "प्रसव के बाद दिन {n}", "Generated": "तैयार किया गया",
  "Check-in trends": "चेक-इन के ट्रेंड", "EPDS scores": "ईपीडीएस स्कोर", "Q10 positive": "प्रश्न 10 सकारात्मक", "No screening completed yet.": "अभी तक कोई जाँच पूरी नहीं हुई।",
  "AMBER / RED symptoms": "नारंगी / लाल लक्षण", "advised:": "सलाह:", "emergency care": "आपातकालीन इलाज", "see doctor within 24 h": "24 घंटे के भीतर डॉक्टर को दिखाएँ",
  "None recorded.": "कोई दर्ज नहीं।", "Missed check-ins": "छूटे हुए चेक-इन", "{a} of the last {b} days": "पिछले {b} दिनों में से {a}",
  "Screening support, not a diagnosis. Generated by AfterBloom from patient-entered data.": "यह जाँच में सहायता है, रोग का निदान नहीं। आफ्टरब्लूम द्वारा मरीज़ की दर्ज की गई जानकारी से तैयार।",
  "Send a weekly \"How to help this week\" note": "साप्ताहिक \"इस सप्ताह कैसे मदद करें\" नोट भेजें",
  "Goes only to family you have allowed. No symptoms, scores or health details.": "केवल उन्हीं परिवारजनों को जाता है जिन्हें आपने अनुमति दी है। इसमें कोई लक्षण, स्कोर या स्वास्थ्य संबंधी जानकारी नहीं होती।",
  "Preview": "पूर्वावलोकन",
  "AfterBloom summary for {name} (day {n} postpartum)": "{name} के लिए आफ्टरब्लूम सारांश (प्रसव के बाद दिन {n})",
  "EPDS:": "ईपीडीएस:", "AMBER/RED symptoms:": "नारंगी/लाल लक्षण:", "Check-ins in last 7 days:": "पिछले 7 दिनों में चेक-इन:",
  "Week 1: rest is your job right now. Heavy tiredness and tears are common.": "सप्ताह 1: अभी आपका काम आराम करना है। बहुत थकान और आँसू आना आम बात है।",
  "Week 2: the baby blues often peak and then ease. If sadness stays, tell your care team.": "सप्ताह 2: बेबी ब्लूज़ अक्सर चरम पर पहुँचकर फिर कम होते हैं। अगर उदासी बनी रहे तो अपनी देखभाल टीम को बताइए।",
  "Week 3: many mothers feel overwhelmed now. Ask for one concrete thing from your family today.": "सप्ताह 3: इस समय कई माँएँ बोझिल महसूस करती हैं। आज अपने परिवार से कोई एक ठोस मदद माँगिए।",
  "Week 4: feeding settles into a pattern. A short walk and sunlight can lift your mood.": "सप्ताह 4: दूध पिलाने की एक लय बन जाती है। थोड़ी सैर और धूप से मूड बेहतर हो सकता है।",
  "Week 5: you may be feeling stronger. Keep your six-week check-up booked.": "सप्ताह 5: हो सकता है आप ज़्यादा मज़बूत महसूस कर रही हों। अपनी छह सप्ताह की जाँच की बुकिंग बनाए रखिए।",
  "Week 6: time for your postnatal check-up. Take your one-page summary with you.": "सप्ताह 6: प्रसवोत्तर जाँच का समय। अपना एक पृष्ठ का सारांश साथ ले जाइए।",
  "You are doing a wonderful job. Keep checking in on yourself.": "आप बहुत अच्छा कर रही हैं। अपना हालचाल लेती रहिए।",

  // ---------- privacy ----------
  "Privacy and safety": "गोपनीयता और सुरक्षा", "Built for homes where a phone is shared.": "उन घरों के लिए बनाया गया जहाँ फ़ोन साझा होता है।",
  "PIN lock": "पिन लॉक", "PIN lock is on.": "पिन लॉक चालू है।", "Lock now": "अभी लॉक करें", "Turn off": "बंद करें", "Choose a 4-digit PIN": "4 अंकों का पिन चुनें",
  "The crisis button always works, even when locked. The": "संकट का बटन हमेशा काम करता है, लॉक होने पर भी। ऊपर का", "button at the top leaves AfterBloom instantly and locks the app.": "बटन आपको तुरंत आफ्टरब्लूम से बाहर ले जाता है और ऐप को लॉक कर देता है।",
  "Consent controls": "सहमति नियंत्रण", "Neutral notifications": "तटस्थ सूचनाएँ",
  "Shown as: \"You have a new message\"": "ऐसे दिखेगा: \"आपके लिए एक नया संदेश है\"", "Shown with details, e.g. \"Time for your mind check\"": "विवरण के साथ दिखेगा, जैसे \"आपकी मन की जाँच का समय\"",
  "Share check-in trends with my professional": "मेरे चेक-इन के ट्रेंड मेरे विशेषज्ञ के साथ साझा करें", "Weekly \"how to help\" note to family": "परिवार को साप्ताहिक \"कैसे मदद करें\" नोट",
  "Who looked at my record": "मेरा रिकॉर्ड किसने देखा", "Every professional view is logged and kept for at least a year.": "विशेषज्ञ द्वारा हर बार देखे जाने का रिकॉर्ड रखा जाता है और कम से कम एक वर्ष तक सुरक्षित रखा जाता है।",
  "Our promises": "हमारे वादे",
  "No advertising, ever. Your baby's data is never used for any commercial purpose. You are the consenting parent for your baby's data (DPDP Act).": "कभी कोई विज्ञापन नहीं। आपके बच्चे की जानकारी का उपयोग कभी किसी व्यावसायिक उद्देश्य के लिए नहीं होता। अपने बच्चे की जानकारी के लिए सहमति देने वाली अभिभावक आप हैं (डीपीडीपी अधिनियम)।",
  "Reset all demo data?": "सारा डेमो डेटा रीसेट करें?", "Reset demo data": "डेमो डेटा रीसेट करें",
  "System": "सिस्टम", "Dr. Ananya Rao (sample)": "डॉ. अनन्या राव (नमूना)",

  // ---------- professional dashboard ----------
  "Dr. Ananya Rao's dashboard": "डॉ. अनन्या राव का डैशबोर्ड", "Sorted by urgency. Every view of a record is logged.": "तात्कालिकता के अनुसार क्रमबद्ध। रिकॉर्ड का हर बार देखा जाना दर्ज होता है।",
  "Patients": "मरीज़", "Callbacks ({n})": "कॉलबैक ({n})", "Moderation ({n})": "मॉडरेशन ({n})", "Audit log": "ऑडिट लॉग",
  "No flags": "कोई फ़्लैग नहीं", "URGENT FLAG": "तत्काल फ़्लैग", "Probable depression": "अवसाद की प्रबल संभावना", "Possible depression": "अवसाद की संभावना", "BP logged": "बीपी दर्ज",
  "EPDS bands and history": "ईपीडीएस श्रेणियाँ और इतिहास", "No screening yet.": "अभी कोई जाँच नहीं।", "Mood, sleep, appetite": "मूड, नींद, भूख",
  "AMBER/RED symptoms": "नारंगी/लाल लक्षण", "None.": "कोई नहीं।", "Select a patient to see their record.": "रिकॉर्ड देखने के लिए किसी मरीज़ को चुनें।",
  "No pending callbacks. Try an EPDS score of 13+ or question 10 as Priya.": "कोई लंबित कॉलबैक नहीं। प्रिया के रूप में ईपीडीएस स्कोर 13+ या प्रश्न 10 आज़माएँ।",
  "URGENT: immediate callback": "तत्काल: अभी कॉलबैक करें", "Callback within 24-48 h": "24-48 घंटे के भीतर कॉलबैक", "Flagged": "फ़्लैग किया गया", "due by": "समय-सीमा",
  "Messages flagged for self-harm language in Bloom Circles. The software never replies on its own; a human decides.": "ब्लूम सर्कल में खुद को नुकसान पहुँचाने वाली भाषा के लिए फ़्लैग किए गए संदेश। सॉफ़्टवेयर कभी अपने आप जवाब नहीं देता; निर्णय इंसान लेता है।",
  "Queue is empty. Post self-harm language in the Circle to test.": "कतार खाली है। जाँच के लिए सर्कल में खुद को नुकसान पहुँचाने वाली भाषा वाली पोस्ट डालें।",
  "Reach out to her": "उनसे संपर्क करें", "Hide post": "पोस्ट छिपाएँ",
  "EPDS 15, mood falling": "ईपीडीएस 15, मूड गिर रहा है", "EPDS 11 twice, BP logged": "ईपीडीएस 11 दो बार, बीपी दर्ज", "EPDS 6, checking in daily": "ईपीडीएस 6, रोज़ चेक-इन कर रही हैं",
  "Open urgent flag": "तत्काल फ़्लैग खुला है", "Recovering well": "अच्छी तरह स्वस्थ हो रही हैं",
  
  "ASHA worker dashboard": "आशा कार्यकर्ता डैशबोर्ड", "Mothers in your area, sorted by risk, so you visit the ones who need you most.": "आपके क्षेत्र की माँएँ, जोखिम के अनुसार क्रमबद्ध, ताकि आप उनसे पहले मिलें जिन्हें आपकी सबसे ज़्यादा ज़रूरत है।",
  "Good morning": "सुप्रभात", "Good afternoon": "नमस्ते", "Good evening": "शुभ संध्या", "Be gentle with yourself today.": "आज अपने साथ नरमी से पेश आएँ।",
  "You've checked in today. Thank you.": "आपने आज चेक-इन कर लिया। धन्यवाद।", "How are you feeling today?": "आज आप कैसा महसूस कर रही हैं?",
  "Rest if you can. Come back tomorrow, or any time something feels different.": "हो सके तो आराम करें। कल फिर आएँ, या जब भी कुछ अलग लगे।",
  "A 30-second check on your mood, sleep and body. No right or wrong answers.": "आपके मूड, नींद और शरीर की 30 सेकंड की जाँच। कोई जवाब सही या गलत नहीं।",
  "Start my check-in": "मेरा चेक-इन शुरू करें", "This week for you": "इस सप्ताह आपके लिए", "done": "हो गया",
  "Checked in {n} of 7 days": "7 में से {n} दिन चेक-इन किया", "Check-ins this week": "इस सप्ताह के चेक-इन", "checked in": "चेक-इन किया", "not checked in": "चेक-इन नहीं किया",
  "Support, when you want it": "सहारा, जब भी आप चाहें", "Check a symptom": "लक्षण जाँचें","Mothers like you": "आप जैसी माँएँ", "Invite your people": "अपनों को जोड़ें", "Free help": "मुफ़्त मदद",
  "Skip to content": "मुख्य सामग्री पर जाएँ", "Language": "भाषा", "Menu": "मेन्यू", "Main": "मुख्य", "Delete": "मिटाएँ",
  "Switch to dark mode": "डार्क मोड चालू करें", "Switch to light mode": "लाइट मोड चालू करें",
  "How are you feeling?": "आप कैसा महसूस कर रही हैं?", "What have you noticed in your baby?": "आपने अपने शिशु में क्या देखा?",
  "e.g. sar mein bahut dard aur dhundhla dikh raha hai": "जैसे: सिर में बहुत दर्द और धुंधला दिख रहा है", "Try an example": "एक उदाहरण आज़माएँ",
  "Tap the one that fits best.": "जो सबसे सही लगे उस पर टैप करें।", "Free help: Tele-MANAS": "मुफ़्त मदद: टेली-मानस", "Free: Tele-MANAS": "मुफ़्त: टेली-मानस",
  "Tell us what you feel in English, Hindi or Hinglish. We match your words to known symptoms. The advice is always pre-written and clinician-reviewed.": "अंग्रेज़ी, हिंदी या हिंग्लिश में बताइए कि आप कैसा महसूस कर रही हैं। हम आपके शब्दों को जाने-पहचाने लक्षणों से मिलाते हैं। सलाह हमेशा पहले से लिखी और चिकित्सक द्वारा जाँची हुई होती है।",
  "Who is this for?": "यह किसके लिए है?", "Step {a} of {b}": "चरण {a} / {b}", "Your bloom: {n} of 7 days": "आपका फूल: 7 में से {n} दिन",
  "Update today's check-in": "आज का चेक-इन बदलें", "Broken sleep counts too. Add it all up.": "टुकड़ों में सोना भी गिना जाता है। सब जोड़ लें।",
  "Thank you for checking in. Everything looks fine today.": "चेक-इन करने के लिए धन्यवाद। आज सब ठीक लग रहा है।",
  "Next": "आगे", "Very low": "बहुत उदास", "Okay": "ठीक-ठाक", "Good": "अच्छा", "Great": "बहुत अच्छा",
  "Free help any time:": "कभी भी मुफ़्त मदद:", "Thank you for sharing.": "बताने के लिए धन्यवाद।", "Wellness check": "सेहत जाँच",
  "This check is screening support, not a diagnosis.": "यह जाँच केवल स्क्रीनिंग में सहायता है, निदान नहीं।",
  "Overdue by {h}h {m}m": "{h} घं {m} मि की देरी", "Callback due in {h}h {m}m": "कॉलबैक {h} घं {m} मि में देय", "Callback window used": "कॉलबैक की समय-सीमा का उपयोग",
  "Open record": "रिकॉर्ड खोलें", "Callback": "कॉलबैक", "Sample profile": "नमूना प्रोफ़ाइल", "Urgent": "तत्काल", "Open callbacks": "खुले कॉलबैक",
  "Free, 24×7, in 20 languages": "मुफ़्त, 24×7, 20 भाषाओं में", "or call": "या कॉल करें", "Back to AfterBloom": "AfterBloom पर वापस जाएँ",
  "No one has been alerted, because emergency-contact alerts are switched off in your privacy settings.": "किसी को सूचित नहीं किया गया, क्योंकि आपकी गोपनीयता सेटिंग में आपातकालीन संपर्क अलर्ट बंद हैं।",
  "Trend of mood, appetite and sleep over {n} check-ins": "{n} चेक-इन में मूड, भूख और नींद का रुझान", "Blood pressure readings": "रक्तचाप की रीडिंग", "EPDS scores over time": "समय के साथ ईपीडीएस स्कोर",
  "Smarter symptom matching (optional)": "बेहतर लक्षण पहचान (वैकल्प)", "Smarter symptom matching": "बेहतर लक्षण पहचान",
  "Send the words you type (never your name) to our matching service so more ways of describing a symptom are understood. Nothing is stored. Emergency checks always run on your phone first.": "आप जो शब्द लिखती हैं (आपका नाम कभी नहीं) वे हमारी पहचान सेवा को भेजे जाते हैं ताकि लक्षण बताने के ज़्यादा तरीके समझे जा सकें। कुछ भी सहेजा नहीं जाता। आपातकालीन जाँच हमेशा पहले आपके फ़ोन पर ही होती है।",
  "Sends the words you type (never your name) to our matching service so more ways of describing a symptom are understood. Nothing is stored. Emergency checks always run on your phone first.": "आप जो शब्द लिखती हैं (आपका नाम कभी नहीं) वे हमारी पहचान सेवा को भेजे जाते हैं ताकि लक्षण बताने के ज़्यादा तरीके समझे जा सकें। कुछ भी सहेजा नहीं जाता। आपातकालीन जाँच हमेशा पहले आपके फ़ोन पर ही होती है।",
  "Allow": "अनुमति दें", "Not now": "अभी नहीं", "Checking…": "जाँच हो रही है…", "Or choose where it hurts or what is wrong": "या चुनें कि कहाँ दर्द है या क्या दिक्कत है",
  "Just checking": "बस पुष्टि कर रहे हैं", "It sounds like you may have said you do not have this. Do you have: {r}?": "लगता है आपने कहा कि यह नहीं है। क्या आपको यह है: {r}?",
  "Yes, I have this": "हाँ, मुझे यह है", "No, I do not": "नहीं, मुझे नहीं है", "A few quick questions": "कुछ छोटे सवाल", "I am not sure": "मुझे पक्का नहीं पता",
  "Tip: try fewer words, or choose from the list.": "सुझाव: कम शब्द लिखकर देखें, या सूची से चुनें।", "Take the Mind check, a 2-minute wellness check": "माइंड चेक करें, 2 मिनट की सेहत जाँच",
  "Matched with smarter matching.": "बेहतर पहचान से मिलान किया गया।", "Matched on your phone.": "आपके फ़ोन पर मिलान किया गया।",
  "Very severe headache": "बहुत तेज़ सिरदर्द", "Yellow palms or soles in the baby": "बच्चे की हथेलियाँ या तलवे पीले", "Spreading redness or pus at the cord": "नाल पर फैलती लालिमा या मवाद",
  "If this feels like an emergency, call 112": "अगर यह आपातकाल लगे तो 112 पर कॉल करें",
  "Your family has been alerted, as you agreed.": "आपकी सहमति के अनुसार आपके परिवार को सूचित कर दिया गया है।",
  "Hospital": "अस्पताल", "Could not find hospitals here. Search on the map": "यहाँ अस्पताल नहीं मिले। नक्शे पर खोजें",
  "Help now": "मदद", "Need help now?": "अभी मदद चाहिए?",
  "After the baby comes home, everyone checks on the baby.": "बच्चे के घर आने के बाद, सब बच्चे का हाल पूछते हैं।",
  "AfterBloom checks on the mother.": "AfterBloom माँ का हाल पूछता है।",
  "Postpartum care for Indian mothers": "भारतीय माँओं के लिए प्रसवोत्तर देखभाल",
  "A care companion for mothers, their families and their babies.": "माँओं, उनके परिवारों और उनके शिशुओं के लिए देखभाल का साथी।",
  "Start your check-in": "अपना चेक-इन शुरू करें", "I'm a professional": "मैं एक पेशेवर हूँ", "Why we exist": "हम क्यों हैं",
  "The quiet after the hospital": "अस्पताल के बाद की ख़ामोशी",
  "The delivery is watched over with great care. Then you go home, and the weeks that follow have very little support for your own body and mind.": "प्रसव पर पूरा ध्यान रखा जाता है। फिर आप घर आ जाती हैं, और उसके बाद के हफ़्तों में आपके अपने शरीर और मन के लिए बहुत कम सहारा होता है।",
  "of Indian mothers screen positive for postpartum depression, about 1 in 5.": "भारतीय माँओं की प्रसवोत्तर अवसाद की जाँच सकारात्मक आती है, यानी लगभग 5 में से 1।",
  "of maternal deaths happen after delivery and discharge, about one in three. Many warning signs show up at home first.": "मातृ मृत्यु प्रसव और छुट्टी के बाद होती हैं, यानी लगभग हर तीन में से एक। कई चेतावनी संकेत सबसे पहले घर पर ही दिखते हैं।",
  "You are not alone, and none of this is your fault.": "आप अकेली नहीं हैं, और इसमें आपकी कोई ग़लती नहीं है।",
  "What AfterBloom does": "AfterBloom क्या करता है", "For the whole family": "पूरे परिवार के लिए",
  "Her partner, her mother and her mother-in-law get simple, practical ways to help. She chooses who joins and what each person sees.": "उनके साथी, उनकी माँ और सास को मदद करने के आसान, व्यावहारिक तरीक़े मिलते हैं। कौन जुड़े और हर किसी को क्या दिखे, यह वही चुनती हैं।",
  "Mother": "माँ", "Partner": "साथी", "Elder": "बड़े (माँ या सास)",
  "Mother, partner and elder connected around her": "माँ के आसपास जुड़े साथी और बड़े",
  "A mother holding her baby, wrapped in a dupatta": "दुपट्टे में लिपटी एक माँ अपने शिशु को गोद में लिए हुए",
  "A flower in full bloom": "पूरी तरह खिला हुआ फूल",
  "Every new mother deserves someone checking on her.": "हर नई माँ का हाल पूछने वाला कोई होना चाहिए।",
  "Free for mothers, always. Crisis help never needs a login.": "माँओं के लिए हमेशा मुफ़्त। संकट में मदद के लिए लॉगिन कभी ज़रूरी नहीं।",
  "Day {n}": "दिन {n}", "Next HBNC visit: day {a} (in {b} days)": "अगली एचबीएनसी भेंट: दिन {a} ({b} दिन में)", "HBNC visits complete": "एचबीएनसी भेंट पूरी",
  "Real ASHA onboarding and district pilots with NHM. Depression screening is not currently part of HBNC home visits (days 3, 7, 14, 21, 28, 42).": "एनएचएम के साथ असली आशा जुड़ाव और ज़िला स्तर के पायलट। अवसाद की जाँच अभी एचबीएनसी गृह भेंटों (दिन 3, 7, 14, 21, 28, 42) का हिस्सा नहीं है।",
};

export const HI: Record<string, string> = { ...HI_DATA, ...HI_EXTRA, ...HI_DEPTH, ...HI_JOURNEY, ...HI_GROUPING, ...BASE };
