// Builds the "for my doctor" clinical summary as a real, selectable PDF file, client-side, from the data already
// on screen. Replaces window.print(): a system print dialog is not what "Download as PDF" promises, and its
// "Save as PDF" destination is unreliable in a PWA's standalone window on some Android browsers. This produces
// an actual .pdf, downloaded the same way the rest of the app downloads files (lib/actions "export" pattern).
// pdf-lib is loaded on demand (dynamic import) so it never adds to this page's initial bundle.

export type PdfReportData = {
  motherName: string; day: number; delivery: string; dateLabel: string;
  riskLine: string;
  babyWeightLine: string | null;
  checkedDays: number; totalDays: number; avgSleep: string;
  epds: { dateLabel: string; total: number; band: "low" | "possible" | "probable"; selfHarm: boolean }[];
  symptoms: { dateLabel: string; level: "RED" | "AMBER"; labels: string; advice: string }[];
  bp: { dateLabel: string; sys: number; dia: number }[];
  missed: string[];
};

const PAGE_W = 595.28, PAGE_H = 841.89; // A4, in points
const MARGIN = 50;
const BODY_W = PAGE_W - MARGIN * 2;

/** Greedy word-wrap using the font's own metrics, so lines never overrun the page width. */
function wrap(str: string, size: number, font: import("pdf-lib").PDFFont, maxWidth: number): string[] {
  const words = str.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let line = "";
  for (const w of words) {
    const next = line ? `${line} ${w}` : w;
    if (font.widthOfTextAtSize(next, size) > maxWidth && line) { lines.push(line); line = w; } else line = next;
  }
  if (line) lines.push(line);
  return lines.length ? lines : [""];
}

export async function buildReportPdf(d: PdfReportData): Promise<Uint8Array> {
  const { PDFDocument, StandardFonts, rgb } = await import("pdf-lib");
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const ink = rgb(0.23, 0.12, 0.17), muted = rgb(0.42, 0.29, 0.34);

  let page = doc.addPage([PAGE_W, PAGE_H]);
  let y = PAGE_H - MARGIN;
  const ensure = (need: number) => { if (y < MARGIN + need) { page = doc.addPage([PAGE_W, PAGE_H]); y = PAGE_H - MARGIN; } };
  const line = (t: string, size = 11, f = font, color = ink, gap = size + 7) => {
    for (const ln of wrap(t, size, f, BODY_W)) { ensure(gap); page.drawText(ln, { x: MARGIN, y, size, font: f, color }); y -= gap; }
  };
  const heading = (t: string) => { ensure(28); y -= 8; line(t, 13, bold, ink, 18); };

  line("AfterBloom - Clinical summary", 18, bold, ink, 26);
  line(`${d.motherName} - Day ${d.day} after ${d.delivery} - ${d.dateLabel}`, 10, font, muted, 20);

  heading("Recovery profile");
  line(d.riskLine);
  if (d.babyWeightLine) line(d.babyWeightLine);

  heading("Check-in trends (last 14 days)");
  line(`Checked in ${d.checkedDays} of ${d.totalDays} days. Average sleep ${d.avgSleep} h.`);

  heading("Mood screening (EPDS)");
  if (!d.epds.length) line("No screening yet.", 11, font, muted);
  for (const e of d.epds) line(`${e.dateLabel}: ${e.total}/30${e.selfHarm ? " (Q10+)" : ""} - ${e.band}`);

  heading("AMBER and RED symptoms");
  if (!d.symptoms.length) line("None.", 11, font, muted);
  for (const s of d.symptoms) line(`${s.dateLabel} [${s.level}] ${s.labels} - Advised: ${s.advice}`);

  if (d.bp.length) {
    heading("Blood pressure");
    for (const b of d.bp) line(`${b.dateLabel}: ${b.sys}/${b.dia}`);
  }

  heading("Missed check-ins");
  line(d.missed.length ? d.missed.join(", ") : "None in the last 14 days.");

  ensure(30); y -= 8;
  line("Generated by AfterBloom from the mother's own entries. Screening support and care navigation, not a diagnosis.", 8, font, muted, 10);

  return doc.save();
}
