// Ask Bloom's answer library. Every answer is prewritten: the software only chooses WHICH one to show, it never writes new advice.
// No medicine names or doses, no diagnoses. Wording and Hindi are drafts pending sign-off by a doctor (see README, "Items to Confirm").
export type Topic = {
  id: string;
  who: "mother" | "baby" | "family";
  title: string; hi_title: string;
  /** How people actually ask it: English, Hindi and Hinglish. Used for matching only. */
  asks: string[];
  answer: string; hi_answer: string;
  /** "When to see a doctor": always shown when present. */
  watch?: string; hi_watch?: string;
  link?: { href: string; label: string };
  /** Tap-to-call helplines always shown with this answer (for example 181 or 112 on safety topics). */
  call?: { label: string; hi_label: string; number: string }[];
  /** Where the content comes from, and who signed it off. Shown in small print under the answer. */
  source?: string;
  reviewed?: { by: string; on: string };
};

export const TOPICS: Topic[] = [
  // ---------- mother ----------
  { id: "lochia", who: "mother", title: "How long will the bleeding last?", hi_title: "खून कितने दिन तक आएगा?",
    asks: ["how long will I bleed after delivery", "bleeding after birth how many days", "lochia", "postpartum bleeding normal", "delivery ke baad kitne din khoon aata hai", "bleeding kab tak hogi", "प्रसव के बाद खून कितने दिन आता है", "pad kitne din lagana padega"],
    answer: "Bleeding after birth is normal and can last up to 6 weeks. It starts red, then turns pink or brown, then pale yellow or white, and slowly gets lighter. It can look heavier after you have been on your feet a lot or after feeding.",
    hi_answer: "प्रसव के बाद खून आना सामान्य है और 6 हफ़्ते तक चल सकता है। पहले लाल, फिर गुलाबी या भूरा, फिर हल्का पीला या सफ़ेद होता है और धीरे-धीरे कम होता जाता है। ज़्यादा चलने-फिरने या दूध पिलाने के बाद थोड़ा बढ़ा हुआ लग सकता है।",
    watch: "Go to hospital now if you soak a pad in an hour, pass clots bigger than a lemon, or the discharge smells foul or you have fever.",
    hi_watch: "अगर एक घंटे में पैड भीग जाए, नींबू से बड़े थक्के आएँ, बदबूदार स्राव हो या बुखार हो तो अभी अस्पताल जाएँ।" },
  { id: "afterpains", who: "mother", title: "Cramps after delivery", hi_title: "डिलीवरी के बाद पेट में ऐंठन",
    asks: ["cramps after delivery", "stomach pain while breastfeeding", "afterpains", "belly cramps after birth", "pet mein marod delivery ke baad", "feeding ke time pet dard", "दूध पिलाते समय पेट में दर्द", "uterus contracting pain"],
    answer: "Cramps in the first few days are normal. The womb is shrinking back, and feeding can make the cramps stronger for a moment. They usually ease within about a week. A warm cloth on the lower belly and slow breathing can help.",
    hi_answer: "शुरू के कुछ दिनों में ऐंठन सामान्य है। गर्भाशय वापस छोटा हो रहा होता है और दूध पिलाने पर कुछ देर के लिए बढ़ सकती है। यह आमतौर पर एक हफ़्ते में कम हो जाती है। निचले पेट पर गर्म कपड़ा और धीमी साँसें आराम दे सकती हैं।",
    watch: "See a doctor soon if the pain is severe, keeps getting worse, or comes with fever.", hi_watch: "दर्द बहुत तेज़ हो, बढ़ता जाए या बुखार के साथ हो तो जल्दी डॉक्टर को दिखाएँ।" },
  { id: "csection_wound", who: "mother", title: "Caring for a C-section wound", hi_title: "सिज़ेरियन घाव की देखभाल",
    asks: ["how to take care of c section stitches", "c section wound care", "cesarean scar pain", "operation ka ghav kaise saaf rakhein", "sezarian ke tanke", "सिज़ेरियन के टाँके की देखभाल", "when can I lift things after c section", "stitches wet bath"],
    answer: "Keep the wound clean and dry and follow the instructions the hospital gave you. When you cough, laugh or get up, hold a pillow gently against the wound. Avoid lifting anything heavier than your baby until your doctor says it is safe. Wear loose, soft clothes.",
    hi_answer: "घाव को साफ़ और सूखा रखें और अस्पताल की बताई हिदायतें मानें। खाँसते, हँसते या उठते समय घाव पर हल्के से तकिया दबाकर रखें। जब तक डॉक्टर न कहें, बच्चे से भारी कुछ न उठाएँ। ढीले, मुलायम कपड़े पहनें।",
    watch: "See a doctor within a day if the wound is red, swollen, leaking pus, opening up, or you have fever.", hi_watch: "घाव लाल, सूजा हुआ हो, मवाद आए, खुलने लगे या बुखार हो तो एक दिन के अंदर डॉक्टर को दिखाएँ।" },
  { id: "stitches", who: "mother", title: "Caring for stitches after a vaginal birth", hi_title: "नॉर्मल डिलीवरी के टाँकों की देखभाल",
    asks: ["stitches after normal delivery pain", "episiotomy care", "tears stitches healing", "normal delivery ke tanke dard", "tanke kab theek honge", "टाँकों में दर्द", "sitting hurts after delivery", "perineum pain"],
    answer: "Rinse with clean warm water after using the toilet and pat dry, always from front to back. Sitting in a basin of warm water for a few minutes can ease soreness. Change pads often. Soreness usually improves over 1 to 2 weeks.",
    hi_answer: "शौच के बाद साफ़ गुनगुने पानी से धोएँ और थपथपाकर सुखाएँ, हमेशा आगे से पीछे की ओर। कुछ मिनट गुनगुने पानी के टब में बैठने से दर्द में आराम मिल सकता है। पैड जल्दी-जल्दी बदलें। दर्द आमतौर पर 1-2 हफ़्ते में कम हो जाता है।",
    watch: "See a doctor within a day if the area smells bad, has pus, pain is getting worse, or you have fever.", hi_watch: "जगह से बदबू आए, मवाद हो, दर्द बढ़ रहा हो या बुखार हो तो एक दिन के अंदर डॉक्टर को दिखाएँ।" },
  { id: "blues_vs_ppd", who: "mother", title: "Baby blues or something more?", hi_title: "बेबी ब्लूज़ या उससे ज़्यादा?",
    asks: ["why am I crying all the time", "feeling sad after baby", "baby blues", "is this postpartum depression", "am I depressed", "main bahut rona aa raha hai", "bachche ke baad udaas", "मन उदास रहता है", "no bonding with baby", "feeling low after delivery"],
    answer: "Feeling tearful, anxious or moody in the first two weeks is very common (the baby blues) and usually fades by itself. If sadness stays beyond two weeks, gets worse, or stops you eating, sleeping or caring for yourself or your baby, it may be postpartum depression. This is common, it is not your fault, and it gets better with support.",
    hi_answer: "पहले दो हफ़्तों में रोना आना, घबराहट या मूड बदलना बहुत आम है (बेबी ब्लूज़) और अपने आप ठीक हो जाता है। अगर उदासी दो हफ़्ते से ज़्यादा रहे, बढ़ती जाए, या खाना, नींद और अपनी या बच्चे की देखभाल मुश्किल हो जाए, तो यह प्रसवोत्तर अवसाद हो सकता है। यह आम है, आपकी गलती नहीं है, और सहारे से ठीक होता है।",
    watch: "Talk to someone today if the sadness stays. Free help any time: Tele-MANAS 14416. If you have thoughts of harming yourself or your baby, call 112 or 14416 now.", hi_watch: "उदासी बनी रहे तो आज ही किसी से बात करें। मुफ़्त मदद: टेली-मानस 14416। खुद को या बच्चे को नुकसान पहुँचाने के विचार आएँ तो अभी 112 या 14416 पर कॉल करें।",
    link: { href: "/screening", label: "Take the Mind check" } },
  { id: "sleep", who: "mother", title: "I cannot sleep even when the baby sleeps", hi_title: "बच्चा सोता है फिर भी मुझे नींद नहीं आती",
    asks: ["cannot sleep when baby sleeps", "insomnia after delivery", "not sleeping new mom", "how to sleep with newborn", "nind nahi aati", "raat ko neend nahi", "नींद नहीं आती", "tired but cannot sleep"],
    answer: "Broken sleep is expected with a newborn. Try to rest whenever the baby sleeps, and ask your family to take one night feed so you can get 4 to 5 hours in a row. If you lie awake even when you have the chance to sleep, or you feel anxious and racing, tell your doctor or counsellor.",
    hi_answer: "नवजात के साथ टुकड़ों में नींद आना सामान्य है। बच्चा सोए तो आप भी आराम करें, और परिवार से एक रात की फ़ीड सँभालने को कहें ताकि आप लगातार 4-5 घंटे सो सकें। अगर मौका मिलने पर भी नींद न आए, या घबराहट और बेचैनी रहे, तो डॉक्टर या काउंसलर को बताएँ।",
    link: { href: "/family", label: "Plan night feeds with family" } },
  { id: "diet", who: "mother", title: "What should I eat after delivery?", hi_title: "डिलीवरी के बाद क्या खाना चाहिए?",
    asks: ["what to eat after delivery", "postpartum diet", "foods to avoid after birth", "diet while breastfeeding", "delivery ke baad kya khana chahiye", "kya kha sakti hoon", "प्रसव के बाद आहार", "iron foods after delivery", "can I eat fruits after c section"],
    answer: "Eat regular meals with dal, vegetables, fruit, curd or milk, and some protein (eggs, paneer, pulses, fish or chicken if you eat them). Leafy greens, jaggery and dried fruit help with iron. Drink plenty of water. Most home foods are fine. If someone tells you to avoid a food, ask your doctor, because you need enough food to heal and feed your baby. Keep taking any iron or calcium your doctor gave you.",
    hi_answer: "दाल, सब्ज़ियाँ, फल, दही या दूध और कुछ प्रोटीन (अंडा, पनीर, दालें, मछली या चिकन अगर आप खाती हैं) के साथ नियमित खाना खाएँ। पत्तेदार सब्ज़ियाँ, गुड़ और सूखे मेवे आयरन में मदद करते हैं। खूब पानी पिएँ। ज़्यादातर घर का खाना ठीक है। कोई खाना मना करे तो डॉक्टर से पूछें, क्योंकि ठीक होने और दूध पिलाने के लिए आपको भरपूर खाना चाहिए। डॉक्टर ने जो आयरन या कैल्शियम दिया है, लेती रहें।" },
  { id: "exercise", who: "mother", title: "When can I exercise or lift things?", hi_title: "व्यायाम या भारी काम कब शुरू करूँ?",
    asks: ["when can I start exercise after delivery", "walking after c section", "postpartum workout", "yoga after birth", "kab se exercise kar sakti hoon", "bhaari kaam kab", "व्यायाम कब शुरू करें", "pelvic floor exercises"],
    answer: "Gentle walking around the house from the first days is good for you. For anything harder, wait for your check-up, usually at about 6 weeks, and after a C-section wait for your doctor to say yes. Pelvic floor squeezes (tighten as if stopping urine, hold a few seconds, release) can be started gently once you are comfortable.",
    hi_answer: "शुरू के दिनों से घर में हल्का चलना फ़ायदेमंद है। इससे ज़्यादा कुछ भी करने के लिए जाँच तक रुकें, आमतौर पर लगभग 6 हफ़्ते, और सिज़ेरियन के बाद डॉक्टर की हाँ का इंतज़ार करें। पेल्विक फ़्लोर व्यायाम (पेशाब रोकने जैसा कसें, कुछ सेकंड रोकें, छोड़ें) आराम महसूस होने पर धीरे-धीरे शुरू कर सकती हैं।" },
  { id: "intimacy", who: "mother", title: "Intimacy and family planning after birth", hi_title: "प्रसव के बाद शारीरिक संबंध और परिवार नियोजन",
    asks: ["when can we have sex after delivery", "intimacy after birth", "contraception after delivery", "can I get pregnant while breastfeeding", "delivery ke baad sambandh kab", "dobara pregnant", "परिवार नियोजन प्रसव के बाद", "periods not back can I conceive"],
    answer: "There is no fixed date. Most women wait until the bleeding has stopped and they feel comfortable, and many check with their doctor at the 6-week visit. You can become pregnant again even before your periods return and even while breastfeeding, so ask your doctor or ANM about family planning before you restart.",
    hi_answer: "कोई तय तारीख़ नहीं है। ज़्यादातर महिलाएँ खून बंद होने और सहज महसूस करने तक रुकती हैं, और कई 6 हफ़्ते की जाँच में डॉक्टर से पूछती हैं। माहवारी लौटने से पहले और दूध पिलाते हुए भी दोबारा गर्भ ठहर सकता है, इसलिए शुरू करने से पहले डॉक्टर या ANM से परिवार नियोजन के बारे में पूछें।" },
  { id: "constipation", who: "mother", title: "Constipation and piles", hi_title: "कब्ज़ और बवासीर",
    asks: ["constipation after delivery", "piles after birth", "painful stool postpartum", "pet saaf nahi hota", "kabz delivery ke baad", "बवासीर", "hemorrhoids", "afraid to pass stool stitches"],
    answer: "Drink plenty of water, eat fibre (vegetables, fruit, whole grains, dal) and walk a little each day. Do not strain. A warm-water sit can soothe piles. Ask your doctor or pharmacist before taking any medicine for it.",
    hi_answer: "खूब पानी पिएँ, फ़ाइबर (सब्ज़ियाँ, फल, साबुत अनाज, दाल) खाएँ और रोज़ थोड़ा चलें। ज़ोर न लगाएँ। गुनगुने पानी में बैठने से बवासीर में आराम मिल सकता है। कोई भी दवा लेने से पहले डॉक्टर या फ़ार्मासिस्ट से पूछें।",
    watch: "See a doctor if there is heavy bleeding with stool or severe pain.", hi_watch: "मल के साथ ज़्यादा खून आए या बहुत तेज़ दर्द हो तो डॉक्टर को दिखाएँ।" },
  { id: "hair", who: "mother", title: "Hair fall after birth", hi_title: "डिलीवरी के बाद बाल झड़ना",
    asks: ["hair fall after delivery", "losing hair postpartum", "baal jhad rahe hain", "delivery ke baad baal girna", "बाल झड़ना", "when will hair stop falling"],
    answer: "This is very common. It usually starts around 2 to 4 months after birth and settles within a year, and the hair grows back. Eating well, including protein and iron, and gentle hair care help.",
    hi_answer: "यह बहुत आम है। आमतौर पर प्रसव के 2-4 महीने बाद शुरू होता है और साल भर में रुक जाता है, और बाल वापस आ जाते हैं। प्रोटीन और आयरन वाला अच्छा खाना और बालों की हल्की देखभाल मदद करती है।" },
  { id: "engorgement", who: "mother", title: "Hard, painful breasts", hi_title: "स्तनों में सख़्ती और दर्द",
    asks: ["breasts are hard and painful", "engorged breasts", "milk coming in painful", "breast lump while feeding", "stan mein dard", "doodh bhar gaya", "स्तन में गाँठ और दर्द", "mastitis"],
    answer: "When the milk comes in, breasts can feel full and hard for a few days. Feed your baby often, a warm cloth before feeding can help the milk flow, and a cool cloth after feeding eases the swelling. Gently express a little milk if the baby cannot latch.",
    hi_answer: "जब दूध उतरता है तो कुछ दिन स्तन भरे और सख़्त लग सकते हैं। बच्चे को बार-बार दूध पिलाएँ, दूध पिलाने से पहले गर्म कपड़ा दूध बहने में मदद करता है और बाद में ठंडा कपड़ा सूजन कम करता है। बच्चा न पकड़ पाए तो थोड़ा दूध हल्के से निकाल दें।",
    watch: "See a doctor within a day if a part of the breast is red, hot and painful, or you have fever or chills.", hi_watch: "स्तन का कोई हिस्सा लाल, गर्म और दर्द वाला हो या बुखार और कँपकँपी हो तो एक दिन के अंदर डॉक्टर को दिखाएँ।" },
  { id: "nipples", who: "mother", title: "Sore or cracked nipples", hi_title: "निप्पल में दर्द या दरारें",
    asks: ["sore nipples breastfeeding", "cracked nipples", "nipple pain while feeding", "baby latch painful", "nipple mein dard", "निप्पल फटना", "latch kaise karein"],
    answer: "Some tenderness in the first days is common, but pain through the whole feed usually means the latch needs adjusting. The baby should take in the nipple and much of the dark area around it. After feeding, a drop of your own milk spread on the nipple and air drying helps healing. Ask your ANM, ASHA or doctor to watch a feed and help with the latch.",
    hi_answer: "शुरू के दिनों में थोड़ा दर्द आम है, पर पूरे समय दर्द रहे तो आमतौर पर बच्चे की पकड़ (लैच) ठीक करनी होती है। बच्चे के मुँह में निप्पल के साथ उसके आसपास का काला हिस्सा भी ज़्यादातर आना चाहिए। फ़ीड के बाद अपने दूध की एक बूँद निप्पल पर लगाकर हवा में सूखने दें, इससे घाव भरता है। ANM, आशा या डॉक्टर से एक फ़ीड देखकर पकड़ ठीक करवाएँ।",
    watch: "See a doctor if the nipple is bleeding, very painful, or you have fever.", hi_watch: "निप्पल से खून आए, बहुत दर्द हो या बुखार हो तो डॉक्टर को दिखाएँ।" },
  { id: "low_milk", who: "mother", title: "Am I making enough milk?", hi_title: "क्या मेरा दूध काफ़ी है?",
    asks: ["not enough milk", "is my baby getting enough milk", "low milk supply", "how to increase breast milk", "doodh kam hai", "bachcha pet bhar ke peeta hai", "दूध कम बन रहा है", "baby always hungry"],
    answer: "Milk is made on demand: the more your baby feeds, the more you make. Most mothers make enough. Good signs are about 6 or more wet nappies a day from around day 5, regular yellow stools, and a baby who is alert between feeds and gaining weight. Feed often, eat and drink well, and rest when you can.",
    hi_answer: "दूध माँग के हिसाब से बनता है: बच्चा जितना ज़्यादा पीता है, उतना ज़्यादा बनता है। ज़्यादातर माँओं को काफ़ी दूध बनता है। अच्छे संकेत हैं: लगभग पाँचवें दिन से दिन में 6 या ज़्यादा गीले डायपर, नियमित पीला मल, और फ़ीड के बीच जागरूक और वज़न बढ़ाता बच्चा। बार-बार पिलाएँ, अच्छा खाएँ-पिएँ और मौका मिले तो आराम करें।",
    watch: "See a doctor soon if your baby has fewer wet nappies, seems very sleepy or is not gaining weight.", hi_watch: "बच्चे के गीले डायपर कम हों, वह बहुत सोया रहे या वज़न न बढ़े तो जल्दी डॉक्टर को दिखाएँ।",
    link: { href: "/baby", label: "Baby growth log" } },
  { id: "checkups", who: "mother", title: "Which check-ups do I need?", hi_title: "मुझे कौन-कौन सी जाँच करवानी चाहिए?",
    asks: ["when is my postnatal checkup", "6 week checkup", "ASHA home visit", "HBNC visit", "delivery ke baad kab jaana hai doctor", "asha didi kab aayengi", "प्रसवोत्तर जाँच कब", "follow up after delivery"],
    answer: "Your ASHA or ANM usually visits at home on about days 3, 7, 14, 21, 28 and 42 after the birth, and you should have a check-up with your doctor at about 6 weeks. Keep your discharge papers handy and tell them about any worry, big or small.",
    hi_answer: "आपकी आशा या ANM आमतौर पर जन्म के लगभग 3, 7, 14, 21, 28 और 42वें दिन घर आती हैं, और लगभग 6 हफ़्ते पर डॉक्टर से जाँच करवानी चाहिए। डिस्चार्ज के कागज़ात साथ रखें और छोटी-बड़ी हर चिंता उन्हें बताएँ।" },

  // ---------- baby ----------
  { id: "b_feeds", who: "baby", title: "How often should a newborn feed?", hi_title: "नवजात को कितनी बार दूध पिलाना चाहिए?",
    asks: ["how often should newborn feed", "baby feeding schedule", "how many times baby breastfeed", "newborn feeding every 2 hours", "bachche ko kitni baar doodh pilayein", "baby doodh peeta hi rehta hai", "नवजात को कितनी बार दूध", "cluster feeding"],
    answer: "Newborns feed on demand, about 8 to 12 times in 24 hours, so roughly every 2 to 3 hours, including at night. Some feed very often in the evening (cluster feeding), which is normal. Feed when you see early hunger cues such as turning the head, sucking on hands or lip smacking, before crying starts.",
    hi_answer: "नवजात माँग पर दूध पीते हैं, 24 घंटे में लगभग 8 से 12 बार, यानी हर 2-3 घंटे में, रात में भी। कुछ बच्चे शाम को बहुत बार पीते हैं (क्लस्टर फ़ीडिंग), यह सामान्य है। भूख के शुरुआती संकेत दिखें, जैसे सिर घुमाना, हाथ चूसना या होंठ चटकाना, तो रोने से पहले ही पिलाएँ।",
    watch: "Go to the doctor now if the baby will not feed or is very sleepy and hard to wake.", hi_watch: "बच्चा दूध न पिए या बहुत सोया रहे और जगाना मुश्किल हो तो अभी डॉक्टर के पास जाएँ।" },
  { id: "b_only_milk", who: "baby", title: "Water, honey, ghutti or other foods for a newborn", hi_title: "नवजात को पानी, शहद, घुट्टी या और कुछ देना",
    asks: ["can I give my baby honey", "water for newborn in summer", "ghutti for newborn", "gripe water for baby", "when to start solids", "can baby drink water", "bachche ko shahad chatana", "janam ghutti", "nawjaat ko paani dena", "बच्चे को शहद या घुट्टी", "formula or top feed", "when can baby eat food", "baby ko paani pila sakte hain", "garmi mein bachche ko paani", "bachche ko pani dena chahiye", "newborn ko doodh ke alawa kuch", "बच्चे को पानी पिला सकते हैं"],
    answer: "For the first 6 months a baby needs only breast milk, and no water, honey, ghutti, gripe water, tea or animal milk, even in hot weather. Breast milk already has all the water the baby needs. Honey can make a baby under 1 year seriously ill. Start soft home foods at 6 months while you continue breastfeeding.",
    hi_answer: "पहले 6 महीने बच्चे को सिर्फ़ माँ का दूध चाहिए, पानी, शहद, घुट्टी, ग्राइप वॉटर, चाय या जानवर का दूध कुछ नहीं, गर्मी में भी नहीं। माँ के दूध में बच्चे के लिए ज़रूरी पानी पहले से होता है। 1 साल से छोटे बच्चे को शहद देने से वह गंभीर रूप से बीमार हो सकता है। 6 महीने पूरे होने पर दूध पिलाना जारी रखते हुए नरम घर का खाना शुरू करें।",
    watch: "If your baby is not getting enough milk or you are thinking of formula, talk to your doctor or ANM first.", hi_watch: "अगर बच्चे को दूध कम मिल रहा हो या आप फ़ॉर्मूला के बारे में सोच रही हों, तो पहले डॉक्टर या ANM से बात करें।" },
  { id: "b_stool", who: "baby", title: "What is a normal baby poo?", hi_title: "बच्चे का सामान्य मल कैसा होता है?",
    asks: ["baby stool colour", "newborn poop green", "baby poo black", "baby loose motions", "bachche ki potty ka rang", "hari potty", "बच्चे का मल हरा", "how many times should baby poop"],
    answer: "The first stools are black or dark green and sticky (meconium). By about day 5 they turn yellow, soft and seedy in a breastfed baby. Green or a few loose stools can still be normal. Breastfed babies may go several times a day or skip a day or two once they are older than a few weeks.",
    hi_answer: "पहला मल काला या गहरा हरा और चिपचिपा होता है (मेकोनियम)। लगभग पाँचवें दिन तक माँ का दूध पीने वाले बच्चे का मल पीला, नरम और दानेदार हो जाता है। हरा रंग या कुछ पतले मल भी सामान्य हो सकते हैं। कुछ हफ़्तों के बाद बच्चा दिन में कई बार जा सकता है या एक-दो दिन न भी जाए।",
    watch: "See a doctor now if the stool is white or clay-coloured, has blood, is black after the first few days, or the baby has many watery stools and will not feed.", hi_watch: "मल सफ़ेद या मिट्टी जैसा हो, उसमें खून हो, शुरू के दिनों के बाद काला हो, या बच्चे को बहुत पतले दस्त हों और वह दूध न पिए तो अभी डॉक्टर को दिखाएँ।" },
  { id: "b_jaundice", who: "baby", title: "Yellow skin in a newborn (jaundice)", hi_title: "नवजात का पीलापन (पीलिया)",
    asks: ["baby turning yellow", "newborn jaundice", "yellow eyes baby", "baby peela dikh raha hai", "bachche ko piliya", "नवजात पीलिया", "jaundice sunlight", "how long does jaundice last"],
    answer: "Mild yellow colour of the face and eyes is common in the first week and usually fades in 1 to 2 weeks. Feed the baby often, because feeding helps clear it. Sunlight is not a safe treatment, so let a doctor judge how yellow the baby is.",
    hi_answer: "पहले हफ़्ते में चेहरे और आँखों का हल्का पीलापन आम है और आमतौर पर 1-2 हफ़्ते में ठीक हो जाता है। बच्चे को बार-बार दूध पिलाएँ, इससे पीलापन जल्दी उतरता है। धूप सुरक्षित इलाज नहीं है, इसलिए पीलापन कितना है यह डॉक्टर से जँचवाएँ।",
    watch: "Go to hospital now if the yellow reaches the palms or soles, appears in the first 24 hours, or the baby is sleepy, feeding poorly or has pale stools.", hi_watch: "पीलापन हथेलियों या तलवों तक पहुँचे, पहले 24 घंटे में दिखे, या बच्चा सुस्त हो, ठीक से दूध न पिए या मल पीला-सफ़ेद हो तो अभी अस्पताल जाएँ।" },
  { id: "b_cord", who: "baby", title: "Caring for the umbilical cord", hi_title: "नाभि की देखभाल",
    asks: ["umbilical cord care", "baby navel stump", "cord not falling off", "naal ki safai", "nabhi se paani", "नाल की देखभाल", "belly button smell newborn", "can I apply oil on cord"],
    answer: "Keep the cord stump clean and dry and fold the nappy below it so it gets air. Do not apply oil, powder, ash or anything else. It usually dries and falls off in 1 to 2 weeks. If it gets dirty, wash gently with clean water and dry well.",
    hi_answer: "नाल को साफ़ और सूखा रखें और डायपर उसके नीचे मोड़ें ताकि हवा लगे। तेल, पाउडर, राख या कुछ भी न लगाएँ। यह आमतौर पर 1-2 हफ़्ते में सूखकर गिर जाती है। गंदी हो जाए तो साफ़ पानी से हल्के से धोकर अच्छी तरह सुखा दें।",
    watch: "See a doctor now if the skin around it is red or swollen, it has pus or a bad smell, or the baby has fever.", hi_watch: "आसपास की त्वचा लाल या सूजी हो, मवाद या बदबू हो या बच्चे को बुखार हो तो अभी डॉक्टर को दिखाएँ।" },
  { id: "b_sleep", who: "baby", title: "Newborn sleep and safe sleeping", hi_title: "नवजात की नींद और सुरक्षित सोना",
    asks: ["how much should newborn sleep", "baby sleeps all day", "safe sleep for baby", "baby will not sleep at night", "bachcha raat bhar jagta hai", "nawjaat kitna sote hain", "बच्चा रात में नहीं सोता", "can baby sleep on stomach"],
    answer: "Newborns sleep about 14 to 17 hours a day in short stretches and wake to feed, and they do not know night from day yet. For safe sleep, lay the baby on the back on a firm, flat bed with no pillow, loose blankets or soft toys, and keep the room comfortably warm without over-wrapping.",
    hi_answer: "नवजात दिन में लगभग 14 से 17 घंटे छोटे-छोटे हिस्सों में सोते हैं और दूध के लिए जागते हैं, उन्हें अभी दिन-रात का फ़र्क पता नहीं होता। सुरक्षित नींद के लिए बच्चे को पीठ के बल, सख़्त और समतल बिस्तर पर बिना तकिए, ढीले कंबल या नरम खिलौनों के सुलाएँ, और कमरा आरामदायक गर्म रखें, बहुत ज़्यादा न लपेटें।" },
  { id: "b_cry", who: "baby", title: "My baby cries a lot", hi_title: "मेरा बच्चा बहुत रोता है",
    asks: ["baby cries all the time", "colic", "baby crying evening", "baby will not stop crying", "bachcha bahut rota hai", "raat ko rona", "बच्चा बहुत रोता है", "how to soothe a crying baby"],
    answer: "Crying is how babies talk, and it often peaks around 6 weeks. Check the common things first: hunger, a wet nappy, wind (burp after feeds), too hot or too cold. Holding the baby close, swaddling, gentle rocking and soft humming can calm many babies. If you feel overwhelmed, put the baby down safely in the cot and take a few minutes to breathe. Never shake a baby.",
    hi_answer: "रोना बच्चों के बोलने का तरीका है और अक्सर लगभग 6 हफ़्ते पर सबसे ज़्यादा होता है। पहले आम बातें देखें: भूख, गीला डायपर, गैस (दूध के बाद डकार दिलाएँ), ज़्यादा गर्मी या ठंड। बच्चे को पास सटाकर रखना, लपेटना, हल्के झुलाना और धीमे गुनगुनाना कई बच्चों को शांत करता है। अगर आप बहुत थक या घबरा जाएँ तो बच्चे को सुरक्षित पालने में लिटाकर कुछ मिनट साँस लें। बच्चे को कभी न झकझोरें।",
    watch: "See a doctor now if the cry is weak or high-pitched, there is fever, green vomit, a swollen belly, or the baby cannot be comforted and refuses feeds.", hi_watch: "रोना कमज़ोर या बहुत तीखा हो, बुखार, हरी उल्टी या फूला पेट हो, या बच्चा चुप न हो और दूध न ले तो अभी डॉक्टर को दिखाएँ।" },
  { id: "b_fever", who: "baby", title: "Fever in a young baby", hi_title: "छोटे बच्चे को बुखार",
    asks: ["baby has fever", "newborn temperature high", "baby feels hot", "bachche ko bukhar", "bachcha garam lag raha hai", "बच्चे को बुखार", "what temperature is fever in baby", "baby cold hands"],
    answer: "A temperature of 38 degrees C (100.4 degrees F) or more in a baby under 3 months is urgent. Do not give any medicine at home. Take the baby to a doctor or hospital the same day.",
    hi_answer: "3 महीने से छोटे बच्चे में 38 डिग्री सेल्सियस (100.4 डिग्री फ़ारेनहाइट) या ज़्यादा तापमान आपातकालीन माना जाता है। घर पर कोई दवा न दें। उसी दिन बच्चे को डॉक्टर या अस्पताल ले जाएँ।",
    watch: "Also go now if the baby feels very cold, is limp, hard to wake, or is breathing fast.", hi_watch: "बच्चा बहुत ठंडा लगे, ढीला पड़ा हो, जगाना मुश्किल हो या तेज़ साँस ले रहा हो तो भी अभी जाएँ।",
    link: { href: "/check", label: "Use the symptom checker" } },
  { id: "b_spit", who: "baby", title: "Spitting up and hiccups", hi_title: "दूध उलटना और हिचकी",
    asks: ["baby spits up after feeds", "baby hiccups", "baby vomiting milk", "doodh ulat deta hai", "bachche ko hichki", "दूध की उल्टी", "burping baby"],
    answer: "Small spit-ups after feeds and hiccups are common and usually harmless in a baby who is feeding well and gaining weight. Burp the baby during and after feeds and keep the baby upright for 15 to 20 minutes afterwards.",
    hi_answer: "दूध पिलाने के बाद थोड़ा दूध उलटना और हिचकी आना आम है और जो बच्चा ठीक से पी रहा हो और वज़न बढ़ा रहा हो उसके लिए आमतौर पर हानिकारक नहीं। दूध पिलाते समय और बाद में डकार दिलाएँ और बाद में 15-20 मिनट सीधा रखें।",
    watch: "See a doctor now if the vomit is green or forceful, has blood, or the baby is not feeding or losing weight.", hi_watch: "उल्टी हरी या ज़ोर से हो, खून हो, या बच्चा दूध न पिए या वज़न घट रहा हो तो अभी डॉक्टर को दिखाएँ।" },
  { id: "b_vaccines", who: "baby", title: "Which vaccines does my baby need?", hi_title: "बच्चे को कौन-से टीके लगवाने हैं?",
    asks: ["baby vaccination schedule", "which vaccines at birth", "BCG polio hepatitis B", "next vaccine due", "bachche ke teeke", "teekakaran kab", "टीकाकरण सूची", "vaccine side effects fever"],
    answer: "Your baby's first vaccines (BCG, oral polio and hepatitis B) are given at birth or in the first days, and more follow at 6, 10 and 14 weeks and later, under the National Immunization Schedule. Mild fever or a sore, swollen spot after a vaccine is common. Your Baby care page shows what is due and what is overdue for your baby's date of birth.",
    hi_answer: "बच्चे के पहले टीके (बीसीजी, ओरल पोलियो और हेपेटाइटिस बी) जन्म पर या शुरू के दिनों में लगते हैं, और राष्ट्रीय टीकाकरण कार्यक्रम के अनुसार 6, 10 और 14 हफ़्ते पर और उसके बाद भी लगते हैं। टीके के बाद हल्का बुखार या जगह पर दर्द और सूजन आम है। आपके बच्चे की जन्मतिथि के हिसाब से क्या बाकी है यह बेबी केयर पेज पर दिखता है।",
    link: { href: "/baby", label: "Open the vaccine timeline" } },

  // ---------- family ----------
  { id: "f_help", who: "family", title: "How can I help her tonight?", hi_title: "आज रात मैं उसकी कैसे मदद करूँ?",
    asks: ["how can I help my wife after delivery", "what to do for new mother", "how to support postpartum partner", "biwi ki madad kaise karein", "bahu ki dekhbhal", "पत्नी की मदद कैसे करें", "mother in law how to help"],
    answer: "Ask what would help, then do it. Take a night feed so she can sleep 4 to 5 hours in a row. Cook, fill her water bottle and handle the housework without being asked. Listen without giving advice or comparing, and say: \"I am here. You are doing well.\" Protect her from too many visitors and hurtful comments.",
    hi_answer: "पूछें कि क्या मदद चाहिए, फिर वही करें। रात की एक फ़ीड सँभालें ताकि वह लगातार 4-5 घंटे सो सके। खाना बनाएँ, उसकी पानी की बोतल भरें और बिना कहे घर का काम कर लें। सलाह दिए या तुलना किए बिना सुनें, और कहें: \"मैं यहाँ हूँ। तुम अच्छा कर रही हो।\" उसे ज़्यादा मेहमानों और चुभने वाली बातों से बचाएँ।",
    link: { href: "/family-view", label: "Plan night feeds" } },
  { id: "f_ppd", who: "family", title: "Is she sad, or is it depression?", hi_title: "वह उदास है या यह अवसाद है?",
    asks: ["my wife is crying a lot after baby", "how to know if she has postpartum depression", "she is not eating or sleeping", "bahu udaas rehti hai", "wife ro rahi hai", "पत्नी उदास रहती है", "she does not want to hold baby"],
    answer: "Tearfulness for the first two weeks is common. If sadness lasts longer, or she is not eating or sleeping, says she is a bad mother, or does not want to be near the baby, she may have postpartum depression. This is a medical condition, not weakness or ingratitude. Be kind, do not say \"you have a healthy baby, why are you sad?\", and help her talk to a counsellor.",
    hi_answer: "पहले दो हफ़्ते रोना आना आम है। अगर उदासी इससे ज़्यादा चले, वह खाना या सोना छोड़ दे, खुद को बुरी माँ कहे, या बच्चे के पास न रहना चाहे, तो यह प्रसवोत्तर अवसाद हो सकता है। यह एक चिकित्सा स्थिति है, कमज़ोरी या नाशुक्री नहीं। प्यार से पेश आएँ, यह न कहें कि \"बच्चा स्वस्थ है, फिर उदास क्यों हो?\", और उसे काउंसलर से बात करने में मदद करें।",
    watch: "If she talks about harming herself or the baby, sees or hears things others do not, or has not slept for days, call 112 now. Free help: Tele-MANAS 14416.", hi_watch: "अगर वह खुद को या बच्चे को नुकसान की बात करे, ऐसी चीज़ें देखे या सुने जो दूसरों को नहीं दिखतीं, या कई दिनों से न सोई हो तो अभी 112 पर कॉल करें। मुफ़्त मदद: टेली-मानस 14416।" },
];

export const topicById = (id: string) => TOPICS.find((t) => t.id === id);
